### ISSUE TITLE
com.sun.jna.LastErrorException: [104] 

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#1151]
The exception:
```
-------------------------------- Running Tests --------------------------------
mill.scalalib.scalafmt.ScalafmtTests: [4/4] core.reformat 
mill.scalalib.scalafmt.ScalafmtTests: Formatting 2 Scala sources
parsed config (v2.7.5): /home/lefou/work/opensource/mill/.scalafmt.conf
mill.scalalib.scalafmt.ScalafmtTests: [4/4] core.reformat 
mill.scalalib.scalafmt.ScalafmtTests: Everything is formatted already
mill.scalalib.scalafmt.ScalafmtTests: [4/4] core.reformat 
mill.scalalib.scalafmt.ScalafmtTests: Formatting 1 Scala sources
parsed config (v2.7.5): /home/lefou/work/opensource/mill/.scalafmt.conf
mill.scalalib.scalafmt.ScalafmtTests: [1/1] core.buildSources 
+ mill.scalalib.scalafmt.ScalafmtTests.scalafmt.reformat 5081ms  
mill.scalalib.scalafmt.ScalafmtTests: [5/5] mill.scalalib.scalafmt.ScalafmtModule.reformatAll 
mill.scalalib.scalafmt.ScalafmtTests: Formatting 3 Scala sources
parsed config (v2.7.5): /home/lefou/work/opensource/mill/.scalafmt.conf
mill.scalalib.scalafmt.ScalafmtTests: [5/5] mill.scalalib.scalafmt.ScalafmtModule.reformatAll 
mill.scalalib.scalafmt.ScalafmtTests: Everything is formatted already
mill.scalalib.scalafmt.ScalafmtTests: [5/5] mill.scalalib.scalafmt.ScalafmtModule.reformatAll 
mill.scalalib.scalafmt.ScalafmtTests: Formatting 1 Scala sources
parsed config (v2.7.5): /home/lefou/work/opensource/mill/.scalafmt.conf
mill.scalalib.scalafmt.ScalafmtTests: [1/1] core.buildSources 
+ mill.scalalib.scalafmt.ScalafmtTests.scalafmt.reformatAll 3508ms  
java.io.IOException: com.sun.jna.LastErrorException: [104] Die Verbindung wurde vom Kommunikationspartner zurückgesetzt
        at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketInputStream.doRead(UnixDomainSocket.java:151)
        at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketInputStream.read(UnixDomainSocket.java:122)
        at mill.main.client.ProxyStreamPumper.run(ProxyStreamPumper.java:24)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.jna.LastErrorException: [104] Die Verbindung wurde vom Kommunikationspartner zurückgesetzt
        at org.scalasbt.ipcsocket.UnixDomainSocketLibrary.read(Native Method)
        at org.scalasbt.ipcsocket.UnixDomainSocket$UnixDomainSocketInputStream.doRead(UnixDomainSocket.java:149)
        ... 3 more
```

```
09:19:10 ⌁0% θ65° lefou:~/work/opensource/mill master+* 130 ± mill --version
Mill Build Tool version 0.9.3
Java version: 1.8.0_272, vendor: AdoptOpenJDK, runtime: /opt/openjdk-bin-8.272_p10/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "Linux", version: 5.4.80-gentoo-r1-x86_64, arch: amd64
09:19:15 ⌁0% θ64° lefou:~/work/opensource/mill master+* ± mill show main.publishVersion
[1/1] show 
[1/1] show > [2/3] publishVersion 
[1/1] show > [3/3] main.publishVersion 
"0.9.5-20-49d44a"

```

**Comment by lefou** [comment]
This was probably related to newer ipcsocket versions.
