### ISSUE TITLE
java.lang.VerifyError when using TutModule 

### ISSUE THREAD

**Issue by ghostbuster91** [com-lihaoyi/mill#1242]
Hi, 
I am trying to generate documentation for my project. Unfortunately when using TutModule as follow:
```
object docs extends TutModule {
  def scalaVersion = "2.13.3"
  def tutVersion = "0.6.13"
  def moduleDeps = Seq(pgnReader)
}
```
and executing `module.tut` I am getting this error:
```
Exception in thread "main" java.lang.VerifyError: class scala.tools.nsc.interpreter.shell.ReplReporterImpl overrides final method scala.reflect.internal.Reporter.warning(Lscala/reflect/internal/util/Position;Ljava/lang/String;)V
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at tut.IMainPlatform.$anonfun$newInterpreter$1(IMainPlatform.scala:14)
	at tut.felix.IO$Primitive.unsafePerformIO(IO.scala:76)
	at tut.felix.IO$Compute.loop$1(IO.scala:117)
	at tut.felix.IO$Compute.unsafePerformIO(IO.scala:125)
	at tut.felix.Syntax$IOOps.$anonfun$withOut$2(Syntax.scala:34)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withOut(Console.scala:164)
	at tut.felix.Syntax$IOOps.$anonfun$withOut$1(Syntax.scala:34)
	at tut.felix.IO$Primitive.unsafePerformIO(IO.scala:76)
	at tut.felix.IO$Compute.loop$1(IO.scala:121)
	at tut.felix.IO$Compute.unsafePerformIO(IO.scala:125)
	at tut.TutMain$.main(TutMain.scala:8)
	at tut.TutMain.main(TutMain.scala)
```

Mill version: 0.9.3

I wonder if instead of fixing it, the module should be replaced with corresponding MdocModule as tut is deprecated in favor of mdoc (https://github.com/tpolecat/tut).

**Comment by lefou** [comment]
Please keep in mind, that the contrib modules are not as maintained as mill core, but we try to keep all tests successful.

Having a MdocModule sounds like a great idea!

**Comment by lefou** [comment]
Closing this, as tut module is no longer functional. See #1269
