### ISSUE TITLE
java.io.IOException: GetOverlappedResult() failed for read operation: 233

### ISSUE THREAD

**Issue by nornagon** [com-lihaoyi/mill#1310]
When running Mill on Windows I get this error after every command. It seems like the command is otherwise successful, though...

```
java.io.IOException: GetOverlappedResult() failed for read operation: 233
        at org.scalasbt.ipcsocket.Win32NamedPipeSocket$Win32NamedPipeSocketInputStream.read(Win32NamedPipeSocket.java:161)
        at java.io.InputStream.read(Unknown Source)
        at org.scalasbt.ipcsocket.Win32NamedPipeSocket$Win32NamedPipeSocketInputStream.read(Win32NamedPipeSocket.java:134)
        at mill.main.client.ProxyStreamPumper.run(ProxyStreamPumper.java:24)
        at java.lang.Thread.run(Unknown Source)
```

```
> java -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
```

Windows 10 build 19041.928

**Comment by lefou** [comment]
This is a know issue and the reason why `--no-server` option is suggested for mill on Windows.

**Comment by nornagon** [comment]
Where is that suggested? I didn't see any reference to that option in the documentation or README 🤔

**Comment by lefou** [comment]
> Where is that suggested? I didn't see any reference to that option in the documentation or README thinking

https://com-lihaoyi.github.io/mill/mill/Intro_to_Mill.html

> In some environments (such as WSL), mill might have to be run without a server (using `-i`, `--interactive`, `--no-server`, or `--repl`.)

**Comment by nornagon** [comment]
Hm, I'm not using WSL. Perhaps that documentation could be updated to more clearly include Windows?

**Comment by sake92** [comment]
@nornagon does it happen with the latest version? (0.9.9)

**Comment by unkarjedy** [comment]
Reproduced it on Windows with 0.10.0
This was my first experience with mill.
All I did is run `./mill mill.bsp.BSP/install` on this project https://github.com/chpache/test-intellij_scala_2and3
```
$ ./mill mill.bsp.BSP/install
...
Compiling ...\build.sc
[1/1] mill.bsp.BSP.install
Creating BSP connection file: ...\.bsp\mill-bsp.json
Exception in thread "proxyInputStreamThroughPumper" java.lang.RuntimeException: java.io.IOException: GetOverlappedResult() failed for read operation: 233
        at mill.main.client.InputPumper.run(InputPumper.java:51)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: GetOverlappedResult() failed for read operation: 233
        at org.scalasbt.ipcsocket.Win32NamedPipeSocket$Win32NamedPipeSocketInputStream.read(Win32NamedPipeSocket.java:161)
        at java.base/java.io.InputStream.read(InputStream.java:205)

```

**Comment by sake92** [comment]
There is this new library that we can investigate instead of sbt-ipcsocket: https://github.com/kohlschutter/junixsocket  
I'll try when I find some spare time.

**Comment by nemoo** [comment]
Reproduced it on Windows with 0.10.2

I was just trying to install mill manually from: https://github.com/com-lihaoyi/mill/releases/download/0.10.2/0.10.2-assembly

Then I renamed the file to `mill.bat` and ran it:

    C:\dev\mill> .\mill.bat
    Exception in thread "proxyInputStreamThroughPumper" java.lang.RuntimeException: java.io.IOException: GetOverlappedResult() failed for read operation: 233
            at mill.main.client.InputPumper.run(InputPumper.java:51)
            at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: java.io.IOException: GetOverlappedResult() failed for read operation: 233
            at org.scalasbt.ipcsocket.Win32NamedPipeSocket$Win32NamedPipeSocketInputStream.read(Win32NamedPipeSocket.java:161)
            at java.base/java.io.InputStream.read(InputStream.java:205)
            at mill.main.client.InputPumper.run(InputPumper.java:36)
            ... 1 more

Windows 10 Version H2  Build 19042.1586

**Comment by sake92** [comment]
@nornagon @unkarjedy @nemoo Can you try [0.10.3-15-d3d866-assembly](https://github.com/com-lihaoyi/mill/releases/download/0.10.3/0.10.3-15-d3d866-assembly)?  
I made some improvements

**Comment by nemoo** [comment]
@sake92 works for me! Just tried https://github.com/com-lihaoyi/mill/releases/download/0.10.3/0.10.3-15-d3d866-assembly on Windows and the error did not occur anymore.
