### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Invalid Structure field in class com.sun.jna.platform.win32.WinBase$SYSTEM_INFO

### ISSUE THREAD

**Issue by liubenyuan** [com-lihaoyi/mill#1651]
Hi, I try to run the following mill examples,

```scala
// build.sc
import mill._, scalalib._, publish._

trait CommonSpinalModule extends ScalaModule {
  def scalaVersion = "2.13.7"
  def spinalVersion = "1.6.1"

  def scalacOptions = Seq("-unchecked", "-deprecation", "-feature")

  def ivyDeps = Agg(
    ivy"com.github.spinalhdl::spinalhdl-core:$spinalVersion",
    ivy"com.github.spinalhdl::spinalhdl-lib:$spinalVersion",
  )
  def scalacPluginIvyDeps = Agg(ivy"com.github.spinalhdl::spinalhdl-idsl-plugin:$spinalVersion".exclude(
      "*" -> "*"
    )
  )
}

object simple extends CommonSpinalModule with PublishModule {
  def mainClass = Some("mylib.MyTopLevelSim")
  def publishVersion = "0.0.1-SNAPSHOT"

  def pomSettings = PomSettings(
    description = "Simple SpinalHDL Module",
    organization = "com.github.typingArtist",
    url = "https://github.com/typingArtist/SpinalTemplateMill",
    licenses = Seq(License.`LGPL-3.0-or-later`),
    versionControl = VersionControl.github("typingArtist", "SpinalTemplateMill"),
    developers = Seq(
      Developer("typingArtist", "Matthias Wächter", "https://github.com/typingArtist"),
      Developer("Dolu1990", "Dolu1990", "none")
    )
  )
}
```

The versions of java, scala and mill are
```text
PS D:\scala\SpinalTemplateMill> java --version
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)

PS D:\scala\SpinalTemplateMill> mill --version
Mill Build Tool version 0.9.11
Java version: 17.0.1, vendor: Oracle Corporation, runtime: C:\Users\postgres\scoop\apps\openjdk\current
Default locale: en_US, platform encoding: GBK
OS name: "Windows 10", version: 10.0, arch: amd64

PS D:\scala\SpinalTemplateMill> scala --version
Scala code runner version 2.13.7 -- Copyright 2002-2021, LAMP/EPFL and Lightbend, Inc.
```

Though, `mill simple.compile` runs fine but `mill simple.run` failed. and the error messages are
```log
PS D:\scala\SpinalTemplateMill> mill simple.run
[39/39] simple.run
[Runtime] SpinalHDL v1.6.1    git head : 3bf789d53b1b5a36974196e2d591342e15ddf28c
[Runtime] JVM max memory : 16360.0MiB
[Runtime] Current date : 2022.01.05 22:18:40
[Progress] at 0.000 : Elaborate components

**********************************************************************************************
[Warning] Elaboration failed (0 error).
          Spinal will restart with scala trace to help you to find the problem.
**********************************************************************************************

[Progress] at 1.515 : Elaborate components
Exception in thread "main" java.lang.IllegalArgumentException: Invalid Structure field in class com.sun.jna.platform.win32.WinBase$SYSTEM_INFO, field name 'dwActiveProcessorMask' (class com.sun.jna.platform.win32.BaseTSD$DWORD_PTR): The type "com.sun.jna.platform.win32.BaseTSD$DWORD_PTR" is not supported: Can't create an instance of class com.sun.jna.platform.win32.BaseTSD$DWORD_PTR, requires a public no-arg constructor: java.lang.reflect.InvocationTargetException
        at com.sun.jna.Structure.validateField(Structure.java:1246)
        at com.sun.jna.Structure.validateFields(Structure.java:1255)
        at com.sun.jna.Structure.<init>(Structure.java:211)
        at com.sun.jna.Structure.<init>(Structure.java:204)
        at com.sun.jna.Structure.<init>(Structure.java:191)
        at com.sun.jna.Structure.<init>(Structure.java:183)
        at com.sun.jna.platform.win32.WinBase$SYSTEM_INFO.<init>(WinBase.java:441)
        at oshi.hardware.platform.windows.WindowsCentralProcessor.calculateProcessorCounts(WindowsCentralProcessor.java:113)
        at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:113)
        at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:72)
        at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getProcessor(WindowsHardwareAbstractionLayer.java:64)
        at spinal.sim.SimManager$.liftedTree1$1(SimManager.scala:73)
        at spinal.sim.SimManager$.cpuCount$lzycompute(SimManager.scala:71)
        at spinal.sim.SimManager$.cpuCount(SimManager.scala:70)
        at spinal.sim.SimManager$.newCpuAffinity(SimManager.scala:83)
        at spinal.core.fiber.EngineContext.<init>(AsyncCtrl.scala:17)
        at spinal.core.fiber.Engine$.create(AsyncCtrl.scala:143)
        at spinal.core.internals.PhaseCreateComponent.impl(Phase.scala:2261)
        at spinal.core.internals.PhaseContext.doPhase(Phase.scala:181)
        at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$12(Phase.scala:2564)
        at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$12$adapted(Phase.scala:2562)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$7(Phase.scala:2562)
        at spinal.core.ScopeProperty$.sandbox(ScopeProperty.scala:66)
        at spinal.core.internals.SpinalVerilogBoot$.singleShot(Phase.scala:2499)
        at spinal.core.internals.SpinalVerilogBoot$.apply(Phase.scala:2494)
        at spinal.core.Spinal$.apply(Spinal.scala:371)
        at spinal.core.SpinalConfig.generateVerilog(Spinal.scala:164)
        at spinal.core.sim.SpinalSimConfig.compileCloned(SimBootstraps.scala:633)
        at spinal.core.sim.SpinalSimConfig.compile(SimBootstraps.scala:617)
        at spinal.core.sim.SpinalSimConfig.doSim(SimBootstraps.scala:608)
        at mylib.MyTopLevelSim$.main(MyTopLevelSim.scala:13)
        at mylib.MyTopLevelSim.main(MyTopLevelSim.scala)
Caused by: java.lang.IllegalArgumentException: The type "com.sun.jna.platform.win32.BaseTSD$DWORD_PTR" is not supported: Can't create an instance of class com.sun.jna.platform.win32.BaseTSD$DWORD_PTR, requires a public no-arg constructor: java.lang.reflect.InvocationTargetException
        at com.sun.jna.Native.getNativeSize(Native.java:1386)
        at com.sun.jna.Structure.getNativeSize(Structure.java:2284)
        at com.sun.jna.Structure.getNativeSize(Structure.java:2274)
        at com.sun.jna.Structure.validateField(Structure.java:1242)
        ... 34 more
1 targets failed
simple.run subprocess failed
PS D:\scala\SpinalTemplateMill>
```

**Comment by Clonasser** [comment]
Hello! I encountered the same problem on Windows 11. Have you finally resolved it :)

**Comment by Clonasser** [comment]
@lefou THX!  I am trying to configure the SpinalHDL development environment on a new PC. Prior to this, I had already studied Spinal (using IntelliJ) on another Windows 10 system's laptop for a period of time. So when I encountered this error, I first thought about whether it was caused by Windows 11, but soon I realized that there was also this issue on Windows 10 systems, which made me a bit confused.  

But what is “Mill”？I think it is just an alternative to sbt. I configure the development environment following the setup steps provided by spinalhdl documents (https://spinalhdl.github.io/SpinalDoc-RTD/master/SpinalHDL/Getting%20Started/Install%20and%20setup.html). 

In my last configuration process, it was possible to work without Mill (for some reasons, I could only use build.sbt instead of .sc). Therefore, I did not configure mill. The information for my other tools is as follows:
```
C:\Users\Yutong>java -version
java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 1.8.0_381-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.381-b09, mixed mode)

C:\Users\Yutong>scala -version
Scala code runner version 2.12.15 -- Copyright 2002-2021, LAMP/EPFL and Lightbend, Inc.

C:\Users\Yutong>sbt -version
sbt version in this project: 1.9.6
sbt script version: 1.9.6
```

My SBT code is as follows:
```
name := "ODESolver"
version := "1.0"
scalaVersion := "2.12.15"
val spinalVersion = "1.7.0"
val scalatestVersion = "3.2.7"
val breezeVersion = "2.0.1-RC1"


val spinal = Seq(
  // scalaTest
  "org.scalatest" %% "scalatest" % scalatestVersion ,
  "org.scalatest" %% "scalatest" % scalatestVersion % "test",
  // breeze
  "org.scalanlp" %% "breeze" % breezeVersion,
  // spinalHdl
  "com.github.spinalhdl" %% "spinalhdl-core" % spinalVersion,
  "com.github.spinalhdl" %% "spinalhdl-lib" % spinalVersion,
  compilerPlugin("com.github.spinalhdl" %% "spinalhdl-idsl-plugin" % spinalVersion)
)

lazy val root = (project in file(".")).settings(
  libraryDependencies ++= spinal ,
  javaOptions := Seq("-Xmx16G")
)

fork := true
```

When I try to compile any module in my project.  IntelliJ will report an error :(

Eg.,  when I try to run the following code (omitted import&package section)
```
case class lsfr(cfg: ODEConfig) extends Component {
  val io = new Bundle {
    val seed = in Bits (cfg.Length bits) //
    val seed_valid    = in  Bool() //
    val ran_out    = out Bits(cfg.Length bits) //
  }
  noIoPrefix()

  val ran_reg   = Reg(Bits(cfg.Length bits)) init(0)

  when(io.seed_valid){
    ran_reg := io.seed
  }.otherwise {
    for (index <- 0 until cfg.Length) {
      if (index == 0) {
        ran_reg(index) := ran_reg(cfg.Length - 1)
      } else if (index % 3 == 0) {
        ran_reg(index) := ran_reg(cfg.Length - 1) ^ ran_reg(index - 1)
      } else if (index % 5 == 0) {
        ran_reg(index) := ran_reg(cfg.Length - 1) ^ ran_reg(index - 1)
      } else if (index % 7 == 0) {
        ran_reg(index) := ran_reg(cfg.Length - 1) ^ ran_reg(index - 1)
      } else {
        ran_reg(index) := ran_reg(index - 1)
      }
    }
  }
  io.ran_out := ran_reg
}

object lsfrMain {
  val lsfrCfg = ODEConfig()
  def main(args: Array[String]): Unit = {
    val FileDir = "rtl/lsfr"
    SpinalConfig(
      targetDirectory = FileDir,
      oneFilePerComponent = true,
      defaultConfigForClockDomains = ClockDomainConfig(resetActiveLevel = LOW)
    ).generateVerilog(lsfr(lsfrCfg)).printPruned()
  }
}
```

 The full error message is as follows :(
```
[Runtime] SpinalHDL v1.7.0    git head : eca519e78d4e6022e34911ec300a432ed9db8220
[Runtime] JVM max memory : 7225.0MiB
[Runtime] Current date : 2023.10.09 22:45:33
[Progress] at 0.000 : Elaborate components

**********************************************************************************************
[Warning] Elaboration failed (0 error).
          Spinal will restart with scala trace to help you to find the problem.
**********************************************************************************************

[Progress] at 0.235 : Elaborate components
Exception in thread "main" java.lang.IllegalStateException: Unmapped relationship: 7
	at com.sun.jna.platform.win32.WinNT$SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX.fromPointer(WinNT.java:2999)
	at com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformationEx(Kernel32Util.java:715)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.getLogicalProcessorInformationEx(WindowsCentralProcessor.java:168)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.initProcessorCounts(WindowsCentralProcessor.java:158)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:73)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:77)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createProcessor(WindowsHardwareAbstractionLayer.java:60)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:66)
	at spinal.sim.SimManager$.cpuCount$lzycompute(SimManager.scala:72)
	at spinal.sim.SimManager$.cpuCount(SimManager.scala:70)
	at spinal.sim.SimManager$.newCpuAffinity(SimManager.scala:76)
	at spinal.core.fiber.EngineContext.<init>(AsyncCtrl.scala:17)
	at spinal.core.fiber.Engine$.create(AsyncCtrl.scala:143)
	at spinal.core.internals.PhaseCreateComponent.impl(Phase.scala:2345)
	at spinal.core.internals.PhaseContext.doPhase(Phase.scala:181)
	at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$12(Phase.scala:2650)
	at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$12$adapted(Phase.scala:2648)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$7(Phase.scala:2648)
	at spinal.core.ScopeProperty$.sandbox(ScopeProperty.scala:69)
	at spinal.core.internals.SpinalVerilogBoot$.singleShot(Phase.scala:2584)
	at spinal.core.internals.SpinalVerilogBoot$.apply(Phase.scala:2579)
	at spinal.core.Spinal$.apply(Spinal.scala:383)
	at spinal.core.SpinalConfig.generateVerilog(Spinal.scala:165)
	at SC.scfsmMain$.main(scfsm.scala:83)
	at SC.scfsmMain.main(scfsm.scala)

Process finished with exit code 1
```
Thank you very much for your attention. This issue has indeed left me very confused🥺

**Comment by Clonasser** [comment]
I am sorry that this is the full error message, the error just provided is from another module, although they are very similar:
```
[Runtime] SpinalHDL v1.7.0    git head : eca519e78d4e6022e34911ec300a432ed9db8220
[Runtime] JVM max memory : 7225.0MiB
[Runtime] Current date : 2023.10.10 10:09:41
[Progress] at 0.000 : Elaborate components

**********************************************************************************************
[Warning] Elaboration failed (0 error).
          Spinal will restart with scala trace to help you to find the problem.
**********************************************************************************************

[Progress] at 0.213 : Elaborate components
Exception in thread "main" java.lang.IllegalStateException: Unmapped relationship: 7
	at com.sun.jna.platform.win32.WinNT$SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX.fromPointer(WinNT.java:2999)
	at com.sun.jna.platform.win32.Kernel32Util.getLogicalProcessorInformationEx(Kernel32Util.java:715)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.getLogicalProcessorInformationEx(WindowsCentralProcessor.java:168)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.initProcessorCounts(WindowsCentralProcessor.java:158)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:73)
	at oshi.hardware.platform.windows.WindowsCentralProcessor.<init>(WindowsCentralProcessor.java:77)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.createProcessor(WindowsHardwareAbstractionLayer.java:60)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:66)
	at spinal.sim.SimManager$.cpuCount$lzycompute(SimManager.scala:72)
	at spinal.sim.SimManager$.cpuCount(SimManager.scala:70)
	at spinal.sim.SimManager$.newCpuAffinity(SimManager.scala:76)
	at spinal.core.fiber.EngineContext.<init>(AsyncCtrl.scala:17)
	at spinal.core.fiber.Engine$.create(AsyncCtrl.scala:143)
	at spinal.core.internals.PhaseCreateComponent.impl(Phase.scala:2345)
	at spinal.core.internals.PhaseContext.doPhase(Phase.scala:181)
	at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$12(Phase.scala:2650)
	at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$12$adapted(Phase.scala:2648)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at spinal.core.internals.SpinalVerilogBoot$.$anonfun$singleShot$7(Phase.scala:2648)
	at spinal.core.ScopeProperty$.sandbox(ScopeProperty.scala:69)
	at spinal.core.internals.SpinalVerilogBoot$.singleShot(Phase.scala:2584)
	at spinal.core.internals.SpinalVerilogBoot$.apply(Phase.scala:2579)
	at spinal.core.Spinal$.apply(Spinal.scala:383)
	at spinal.core.SpinalConfig.generateVerilog(Spinal.scala:165)
	at SC.lsfrMain$.main(lsfr.scala:71)
	at SC.lsfrMain.main(lsfr.scala)
```

**Comment by lefou** [comment]
@Clonasser Thank for all these details. I appears to me, that your issue is completely with SpinalHDL and not with Mill at all. You said yourself, your not using Mill and the reported stack trace does not contain a single entry originating in Mill. You should report the issue to the SpinalHDL project. This issue tracker is only for Mill, the build tool and it's contrib plugins. Feel free to add a link after you opened an issue there.

I'm going to move this issue into a discussion, as the OP was using Mill, although an old versions, but the issue seems to be unrelated to Mill itself.
