### ISSUE TITLE
Scala Reflect Internal missing in tests

### ISSUE THREAD

**Issue by ex0ns** [com-lihaoyi/mill#1797]
When running some test with scala 2.12.15 I end up with the following error:

```
mill __.test
Compiling /home/ex0ns/projects/crash_mill/build.sc
[60/70] core.test.compile 
[info] compiling 1 Scala source to /home/ex0ns/projects/crash_mill/out/core/test/compile.dest/classes ...
[info] done compiling
[70/70] core.test.test 
- Serialization
  - Room Creation
    Exception in thread "zio-fiber-31" java.lang.NoClassDefFoundError: scala/reflect/internal/Names$Name
        at shapeless.ops.hlist$ToTraversable$$anon$48.builder(hlists.scala:620)
        at shapeless.ops.hlist$ToTraversable.apply(hlists.scala:592)
        at shapeless.ops.hlist$ToTraversable.apply$(hlists.scala:591)
        at shapeless.ops.hlist$ToTraversable$$anon$48.apply(hlists.scala:618)
        at io.circe.generic.extras.encoding.ConfiguredAsObjectEncoder$$anon$1.<init>(ConfiguredAsObjectEncoder.scala:47)
        at io.circe.generic.extras.encoding.ConfiguredAsObjectEncoder$.encodeCaseClass(ConfiguredAsObjectEncoder.scala:46)
        at SerializationSpec$Test$anon$lazy$macro$7$1.inst$macro$1$lzycompute(MainSpec.scala:16)
        at SerializationSpec$Test$anon$lazy$macro$7$1.inst$macro$1(MainSpec.scala:16)
        at SerializationSpec$Test$.<init>(MainSpec.scala:16)
        at SerializationSpec$Test$.<clinit>(MainSpec.scala)
        at SerializationSpec$.$anonfun$spec$1(MainSpec.scala:22)
        at zio.internal.FiberContext.runUntil(FiberContext.scala:242)
        at zio.internal.FiberContext.run(FiberContext.scala:116)
        at zio.internal.ZScheduler$$anon$1.run(ZScheduler.scala:151)
        at zio.internal.FiberContext.runUntil(FiberContext.scala:539)
        at <empty>.SerializationSpec.spec(MainSpec.scala:21)
```

You can find the source at https://github.com/ex0ns/mill_crash/tree/main

Why do I think this is coming from mill ?

 Because I reproduce the exact same setup in scastie: https://scastie.scala-lang.org/ex0ns/UCPKMeUfQRiyV4X46if4Tg/7 (which uses sbt under the hood) and as you can see it works without any issue.

2.13.8 with zio 2.0.0-rc3 => works
2.13.8 with zio 1.0.13 => works

2.12.15 with zio 2.0.0-rc3 => fails
2.12.15 with zio 1.0.13 => fails

I'm using mill 0.10.2 
Feel free to close this issue if you don't think that this is related to mill

**Comment by lefou** [comment]
This doesn't look like an issue in/from Mill.

Isn't `scala/reflect/internal/Names$Name` part of the `scala-reflect` library. Have you added this library to your `ivyDeps` or the classpath?

**Comment by ex0ns** [comment]
If I explicitly add it to my dependencies it works (I should have mentioned that before)

What lead me into thinking that this was a mill issue is that the exact same setup with other build tools works fine.
I've tried to remove zio from the equation (I don't know why I didn't try earlier, sorry for that) and it failed too.


That might be a circe error but I found that the differences between the behavior between sbt and mill a bit strange.
I've updated the reproduction with a even more minimal example

**Comment by lefou** [comment]
Ah, I see. It's now `mill core.run`.

**Comment by lefou** [comment]
I'm not an sbt user. Maybe they default to always bring the scala-reflect to the classpath? At least, the `ivyDepsTree` does not contain a `scala-reflect`. It is most probably a packaging error. I mean the Maven `pom` part of packaging.

```
± mill -i core.ivyDepsTree
[9/9] core.ivyDepsTree 
├─ io.circe:circe-core_2.12:0.14.1
│  ├─ io.circe:circe-numbers_2.12:0.14.1
│  │  └─ org.scala-lang:scala-library:2.12.15
│  ├─ org.scala-lang:scala-library:2.12.15
│  └─ org.typelevel:cats-core_2.12:2.6.1
│     ├─ org.scala-lang:scala-library:2.12.15
│     ├─ org.typelevel:cats-kernel_2.12:2.6.1
│     │  └─ org.scala-lang:scala-library:2.12.15
│     └─ org.typelevel:simulacrum-scalafix-annotations_2.12:0.5.4
│        └─ org.scala-lang:scala-library:2.12.15
├─ io.circe:circe-generic_2.12:0.14.1
│  ├─ com.chuusai:shapeless_2.12:2.3.7
│  │  └─ org.scala-lang:scala-library:2.12.15
│  ├─ io.circe:circe-core_2.12:0.14.1
│  │  ├─ io.circe:circe-numbers_2.12:0.14.1
│  │  │  └─ org.scala-lang:scala-library:2.12.15
│  │  ├─ org.scala-lang:scala-library:2.12.15
│  │  └─ org.typelevel:cats-core_2.12:2.6.1
│  │     ├─ org.scala-lang:scala-library:2.12.15
│  │     ├─ org.typelevel:cats-kernel_2.12:2.6.1
│  │     │  └─ org.scala-lang:scala-library:2.12.15
│  │     └─ org.typelevel:simulacrum-scalafix-annotations_2.12:0.5.4
│  │        └─ org.scala-lang:scala-library:2.12.15
│  └─ org.scala-lang:scala-library:2.12.15
├─ io.circe:circe-generic-extras_2.12:0.14.1
│  ├─ io.circe:circe-generic_2.12:0.14.1
│  │  ├─ com.chuusai:shapeless_2.12:2.3.7
│  │  │  └─ org.scala-lang:scala-library:2.12.15
│  │  ├─ io.circe:circe-core_2.12:0.14.1
│  │  │  ├─ io.circe:circe-numbers_2.12:0.14.1
│  │  │  │  └─ org.scala-lang:scala-library:2.12.15
│  │  │  ├─ org.scala-lang:scala-library:2.12.15
│  │  │  └─ org.typelevel:cats-core_2.12:2.6.1
│  │  │     ├─ org.scala-lang:scala-library:2.12.15
│  │  │     ├─ org.typelevel:cats-kernel_2.12:2.6.1
│  │  │     │  └─ org.scala-lang:scala-library:2.12.15
│  │  │     └─ org.typelevel:simulacrum-scalafix-annotations_2.12:0.5.4
│  │  │        └─ org.scala-lang:scala-library:2.12.15
│  │  └─ org.scala-lang:scala-library:2.12.15
│  └─ org.scala-lang:scala-library:2.12.15
└─ org.scala-lang:scala-library:2.12.15
```
