### ISSUE TITLE
Issue with file names which have symbols (NoSuchElementException)

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#1798]
_Originally posted by @ajrnz in https://github.com/com-lihaoyi/mill/issues/1790#issuecomment-1079721540_

There still appears to be an issue with file names which have symbols.

I have a repo (https://github.com/ajrnz/mill-dep-proj) which I use to make sure that sub/foreign modules work correctly.

It works with 0.9.12 but not with 0.10.2 or the newer snapshots with the patch.

Ie with 0.10.2-9-399bce I get

```
    Exception in thread "MillServerActionRunner" java.util.NoSuchElementException: key not found: ammonite.$file.$up.software$minusversions
	    at scala.collection.MapOps.default(Map.scala:274)
	    at scala.collection.MapOps.default$(Map.scala:273)
	    at scala.collection.AbstractMap.default(Map.scala:405)
	    at scala.collection.mutable.HashMap.apply(HashMap.scala:425)
	    at mill.main.GraphUtils$.scriptNodeOf$1(GraphUtils.scala:16)
	    at mill.main.GraphUtils$.$anonfun$linksToScriptNodeGraph$1(GraphUtils.scala:16)
	    at scala.collection.immutable.List.map(List.scala:246)
	    at scala.collection.immutable.List.map(List.scala:79)
	    at mill.main.GraphUtils$.scriptNodeOf$1(GraphUtils.scala:16)
	    at mill.main.GraphUtils$.$anonfun$linksToScriptNodeGraph$2(GraphUtils.scala:22)
	    at scala.collection.Iterator$$anon$9.next(Iterator.scala:577)
	    at scala.collection.mutable.Growable.addAll(Growable.scala:62)
	    at scala.collection.mutable.Growable.addAll$(Growable.scala:57)
	    at scala.collection.immutable.SetBuilderImpl.addAll(Set.scala:396)
	    at scala.collection.immutable.Set$.from(Set.scala:353)
	    at scala.collection.immutable.Set$.from(Set.scala:93)
	    at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	    at scala.collection.IterableOps.map(Iterable.scala:675)
	    at scala.collection.IterableOps.map$(Iterable.scala:675)
	    at scala.collection.AbstractIterable.map(Iterable.scala:926)
	    at mill.main.GraphUtils$.linksToScriptNodeGraph(GraphUtils.scala:22)
	    at mill.main.RunScript$.importTree(RunScript.scala:139)
	    at mill.main.RunScript$.$anonfun$runScript$6(RunScript.scala:81)
	    at ammonite.util.Res$Success.map(Res.scala:67)
	    at mill.main.RunScript$.runScript(RunScript.scala:71)
	    at mill.main.MainRunner.$anonfun$runScript$1(MainRunner.scala:119)
	    at mill.main.MainRunner.watchLoop2(MainRunner.scala:67)
	    at mill.main.MainRunner.runScript(MainRunner.scala:92)
	    at mill.MillMain$.main0(MillMain.scala:310)
	    at mill.main.MillServerMain$.main0(MillServerMain.scala:78)
	    at mill.main.Server.$anonfun$handleRun$1(MillServerMain.scala:193)
	    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ajrnz** [comment]
This is caused by #1663 and #1788.

I don't understand exactly what #1788 is solving with hyphens  but I can see where it is going wrong. Consider a `build.sc`:

```scala
import $file.^.`parent-hyphen-file`
import $file.`hyphen-file`
```

where the relevant files exist (they can be empty). The latest branch fails on the second line but not the first, with:

    Exception in thread "MillServerActionRunner" java.util.NoSuchElementException: key not found: ammonite.$file.hyphen$minusfile

The cause is the calculation of `withoutCompanions` in `AmmoniteUtils#normalizeAmmoniteImportPath`. I am not exactly which 'companions' the line is filtering out but it removes the `$minusfile` from `ammonite.$file.hyphen$minusfile` resulting in `ammonite.$file.hyphen` which is clearly incorrect. This also happens to `../parent-hyphen-file` but somehow it still appears to work. The happens in calls to `RunScript#importTree`

It is a two stage process
* The first call is with `List(ammonite, $file, hyphen-file)` which results in `List(ammonite, $file, hyphen$minusfile)` as expected
* The second call is with `List(ammonite, $file, hyphen$minusfile)` which results in `List(ammonite, $file, hyphen)` (which is incorrect)

So the function is not idempotent and either `withoutCompanions` needs to be changed or `normalizeAmmoniteImportPath` cannot be called on a pre-normalized path.

@lolgab Can you have a look as I suspect that you understand what is trying to be accomplished

**Comment by lolgab** [comment]
Hi @ajrnz!
Thank you for the accurate analysis and sorry that my change broke your build!
The idea behind withoutCompanions is to have a single entry per file, so if there is a companion object in a file we have a single entry in the Map instead of multiple.
The problem here seems to be that withoutCompanion doesn't consider that the $ symbol is also used by the scala compiler to define symbols. So probably withoutCompanions needs to be adjusted.
But I will give a proper look at this once I'm back at the computer.

**Comment by ajrnz** [comment]
Hi @lolgab. Did you have any further thoughts on this? I'm effectively stuck on 0.9.12 due to this and some other 0.10 bugs. (Ironically I was trying to upgrade to try out your scalablytyped module - which works well on a simplified project structure)

Maybe we could use a different escape character? Say @ instead of $. I not really sure why they are being escaped. Do they need to be valid symbols?
