### ISSUE TITLE
mill -i MyTest.test.testOnly fails

### ISSUE THREAD

**Issue by pxs7** [com-lihaoyi/mill#1879]
gcd.GCDSpec *** ABORTED ***
  java.lang.NoClassDefFoundError: chisel3/MultiIOModule
  at chiseltest.internal.VerilatorBackendAnnotation$.<init>(Testers2.scala:127)
  at chiseltest.internal.VerilatorBackendAnnotation$.<clinit>(Testers2.scala)
  at chiseltest.experimental.ChiselTestCli.$init$(ChiselTestShell.scala:16)
  at chiseltest.experimental.ChiselTestShell.<init>(ChiselTestShell.scala:22)
  at chiseltest.ChiselScalatestTester$TestBuilder.apply(ChiselScalatestTester.scala:26)
  at gcd.GCDSpec.$anonfun$new$1(GCDSpec.scala:24)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  ...
  Cause: java.lang.ClassNotFoundException: chisel3.MultiIOModule
  at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
  at mill.api.ClassLoader$$anon$1.findClass(ClassLoader.scala:47)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
  at chiseltest.internal.VerilatorBackendAnnotation$.<init>(Testers2.scala:127)
  at chiseltest.internal.VerilatorBackendAnnotation$.<clinit>(Testers2.scala)
  at chiseltest.experimental.ChiselTestCli.$init$(ChiselTestShell.scala:16)
  at chiseltest.experimental.ChiselTestShell.<init>(ChiselTestShell.scala:22)
  at chiseltest.ChiselScalatestTester$TestBuilder.apply(ChiselScalatestTester.scala:26)
  at gcd.GCDSpec.$anonfun$new$1(GCDSpec.scala:24)

**Comment by lefou** [comment]
This is not enough context to make this issue useful

**Comment by sequencer** [comment]
It should report to chisel-template rather than mill.
@pxs7 can you send issue there?
