### ISSUE TITLE
Duplicated item inserted into OrderedSet, Exception in thread "MillServerActionRunner"

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#2289]
Mill 0.10.10

The exception does not occur without the `-j 0` option.

```
mill -j 0 __.compile
[#11] [108/3859] framework.domainmodelApi.sources 
[#11] [2970/3859] module.building.osgiHeaders 
[#06] Exception in thread "MillServerActionRunner" java.lang.Exception: Duplicated item inserted into OrderedSet: mill.define.Task$TraverseCtx@67913306
[#06]   at mill.api.AggWrapper$Agg$Mutable.append(AggWrapper.scala:60)
[#06]   at mill.api.AggWrapper$Agg$.$anonfun$from$1(AggWrapper.scala:47)
[#06]   at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
[#06]   at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
[#06]   at scala.collection.immutable.NewVectorIterator.foreach(Vector.scala:2005)
[#06]   at mill.api.AggWrapper$Agg$.from(AggWrapper.scala:47)
[#06]   at mill.eval.Evaluator.parallelEvaluate(Evaluator.scala:337)
[#06]   at mill.eval.Evaluator.evaluate(Evaluator.scala:161)
[#06]   at mill.main.RunScript$.evaluateNamed(RunScript.scala:363)
[#06]   at mill.main.RunScript$.evaluate(RunScript.scala:349)
[#06]   at mill.main.RunScript$.$anonfun$evaluateTasks$1(RunScript.scala:314)
[#06]   at scala.util.Either.map(Either.scala:382)
[#06]   at mill.main.RunScript$.evaluateTasks(RunScript.scala:312)
[#06]   at mill.main.RunScript$.$anonfun$runScript$8(RunScript.scala:105)
[#06]   at ammonite.util.Res$Success.flatMap(Res.scala:62)
[#06]   at mill.main.RunScript$.runScript(RunScript.scala:104)
[#06]   at mill.main.MainRunner.$anonfun$runScript$1(MainRunner.scala:119)
[#06]   at mill.main.MainRunner.watchLoop2(MainRunner.scala:67)
[#06]   at mill.main.MainRunner.runScript(MainRunner.scala:92)
[#06]   at mill.MillMain$.main0(MillMain.scala:320)
[#06]   at mill.main.MillServerMain$.main0(MillServerMain.scala:79)
[#06]   at mill.main.Server.$anonfun$handleRun$1(MillServer
```

**Comment by lihaoyi** [comment]
I suspect this should be fixed in 0.11.x, possibly in https://github.com/com-lihaoyi/mill/pull/2498, which overhauls the `sequentialEvaluate`/`parallelEvaluate` logic
