### ISSUE TITLE
Thread.stop unsupported on JDK 20

### ISSUE THREAD

**Issue by nihil-admirari** [com-lihaoyi/mill#2429]
Running `mill --version` under JDK 20 results in:

```
java.lang.UnsupportedOperationException
	at java.base/java.lang.Thread.stop(Thread.java:1705)
	at mill.main.Server.handleRun(MillServerMain.scala:209)
	at mill.main.Server.$anonfun$run$2(MillServerMain.scala:117)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at mill.main.Server$.lockBlock(MillServerMain.scala:227)
	at mill.main.Server.$anonfun$run$1(MillServerMain.scala:98)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at mill.main.Server$.tryLockBlock(MillServerMain.scala:235)
	at mill.main.Server.run(MillServerMain.scala:95)
	at mill.main.MillServerMain$.main(MillServerMain.scala:53)
	at mill.main.MillServerMain.main(MillServerMain.scala)
```

**Comment by Sailsman63** [comment]
Interestingly, the Oracle [release notes](https://www.oracle.com/java/technologies/javase/20all-relnotes.html) point out that `Thread.stop()` has been deprecated since JDK 1.2 as inherently unsafe.

**Comment by typingArtist** [comment]
https://inside.java/2022/11/09/quality-heads-up/

**Comment by zhutmost** [comment]
I met the same situation.
My mill version is 0.11.0-M8 & 0.10.12, OS platform is macOS.
My JDK version is:
```bash
$ java -version
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment Temurin-20.0.1+9 (build 20.0.1+9)
OpenJDK 64-Bit Server VM Temurin-20.0.1+9 (build 20.0.1+9, mixed mode, sharing)
```
