### ISSUE TITLE
On Windows, Mill requires Java 11

### ISSUE THREAD

**Issue by alexarchambault** [com-lihaoyi/mill#2441]
Currently happening to me with Mill `0.10.12`. On Windows, Mill refuses to start with Java 8:
```text
> java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b09, mixed mode)

> mill -i …
Launching Mill as sub-process ...
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/github/alexarchambault/windowsansi/WindowsAnsi has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at mill.MillMain$.main(MillMain.scala:38)
        at mill.MillMain.main(MillMain.scala)
```

That seems to originate from the (I mean, my) windows-ansi library. The latest `0.0.4` version was inadvertently built with Java 11 (default version shipping with the GitHub runner now, it seems). Its upcoming `0.0.5` version should fix that, thanks to https://github.com/alexarchambault/windows-ansi/pull/91.

**Comment by lefou** [comment]
Thanks for reporting and fixing.
