### ISSUE TITLE
`MatchError: ImportTree` when testing with Mill 0.11.0-M8

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#2460]
```
Output of failed test: 01-simple
---------- Output for Invocation: TestInvocationResult(Targets(targets=List(-d, verify1),expectedExitCode=0,env=Map(),noServer=true),Failed,Vector(),Vector(),Some(/home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/out-9652918657113142208.log))
1 targets failed
parseBuildFiles scala.MatchError: ImportTree(List(($exec,12)),List((plugins,None)),7,42) (of class mill.runner.ImportTree)
    mill.runner.FileImportGraph$.$anonfun$parseBuildFiles$5(FileImportGraph.scala:75)
    mill.runner.FileImportGraph$.$anonfun$parseBuildFiles$5$adapted(FileImportGraph.scala:74)
    scala.collection.immutable.List.foreach(List.scala:333)
    mill.runner.FileImportGraph$.walkStmt$1(FileImportGraph.scala:74)
    mill.runner.FileImportGraph$.$anonfun$parseBuildFiles$3(FileImportGraph.scala:57)
    scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
    scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
    scala.collection.AbstractIterable.foreach(Iterable.scala:933)
    scala.collection.IterableOps$WithFilter.foreach(Iterable.scala:903)
    mill.runner.FileImportGraph$.walkScripts$1(FileImportGraph.scala:56)
    mill.runner.FileImportGraph$.parseBuildFiles(FileImportGraph.scala:102)
    mill.runner.MillBuildRootModule.$anonfun$parseBuildFiles$3(MillBuildRootModule.scala:47)

---------- End of output
```

I assume, the `import $exec` is not supported.

The `build.sc` looks as follows:

```scala
// mill plugins under test
import $exec.plugins
// generated by mill
import $exec.shared

import de.tobiasroeser.mill.vcs.version._
import mill._
import mill.define.Command

val baseDir = build.millSourcePath

def initVcs: T[Unit] =
  T {
    if (!os.exists(baseDir / ".git")) {
      T.log.info("Initializing git repo...")
      Seq(
        os.proc("git", "init"),
        os.proc("git", "config", "user.email", "mill@tototec.de"),
        os.proc("git", "config", "user.name", "Mill CI"),
        os.proc("git", "add", "build.sc"),
        os.proc("git", "commit", "-m", "first commit"),
        os.proc("git", "tag", "1.2.3"),
        os.proc("git", "add", "plugins.sc"),
        os.proc("git", "commit", "-m", "second commit")
      ) foreach (_.call(cwd = baseDir))
    }
    ()
  }

def verify1(): Command[Unit] =
  T.command {
    initVcs()
    val vcsState = VcsVersion.vcsState()
    assert(vcsState.vcs == Some(Vcs.git))

    val version = vcsState.format()
    T.log.info(s"version=${version}")
    assert(version.startsWith("1.2.3-1-") && !version.contains("DIRTY"))
    ()
  }

def changeSomething(): Command[Unit] = T.command {
  os.write.append(baseDir / "plugins.sc", "\n// dummy text")
  ()
}

def verify2(): Command[Unit] =
  T.command {
    initVcs()
    val version = VcsVersion.vcsState().format()
    T.log.info(s"version=${version}")
    assert(version.startsWith("1.2.3-1-") && version.contains("DIRTY"), s"Version was: ${version}")
    ()
  }

```

`plugins.sc`

```scala
// Import a locally published version of the plugin under test
import $ivy.`de.tototec:de.tobiasroeser.mill.vcs.version_mill0.11.0-M8_2.13:0.3.0-22-a7ac47-DIRTYb02b920b`
```

and `shared.sc`

```scala
import $ivy.`org.scoverage::scalac-scoverage-runtime:2.0.8`
```

After changing the `$exec` to `$file`, I get some other exception.

```
Output of failed test: 01-simple
---------- Output for Invocation: TestInvocationResult(Targets(targets=List(-d, verify1),expectedExitCode=0,env=Map(),noServer=true),Failed,Vector(),Vector(),Some(/home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/out-4443420111519312397.log))
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 0 products, 0 sources, 0 libraries
[debug] current source = Set(/home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/out/mill-build/generateScriptSources.dest/millbuild/build.sc, /home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/out/mill-build/generateScriptSources.dest/millbuild/plugins.sc, /home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/out/mill-build/generateScriptSources.dest/millbuild/shared.sc)
[debug] > initialChanges = InitialChanges(Changes(added = Set(/home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/out/mill-build/generateScriptSources.dest/millbuild/plugins.sc, /home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/out/mill-build/generateScriptSources.dest/millbuild/build.sc, /home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/out/mill-build/generateScriptSources.dest/millbuild/shared.sc), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] Full compilation, no sources in previous analysis.
[debug] all 3 sources are invalidated
[debug] Initial set of included nodes: 
[debug] Recompiling all sources: number of invalidated sources > 50.0 percent of all sources
[debug] compilation cycle 1
[info] compiling 3 Scala sources to /home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/out/mill-build/compile.dest/classes ...
[debug] Returning already retrieved and compiled bridge: /home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/mill-scala-compiler-bridge_2.13.10/0.0.1/mill-scala-compiler-bridge_2.13.10-0.0.1.jar.
[debug] [zinc] Running cached compiler 47148f3f for Scala compiler version 2.13.10
[debug] [zinc] The Scala compiler is invoked with:
[debug]         -Xplugin:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/scalac-mill-moduledefs-plugin_2.13.10/0.10.9/scalac-mill-moduledefs-plugin_2.13.10-0.10.9.jar
[debug]         -Xplugin:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/mill-runner-linenumbers_2.13/0.11.0-M8/mill-runner-linenumbers_2.13-0.11.0-M8.jar,/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.10/scala-compiler-2.13.10.jar,/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar,/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.10/scala-reflect-2.13.10.jar,/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12.jar,/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.21.0/jline-3.21.0.jar,/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar
[debug]         -nowarn
[debug]         -bootclasspath
[debug]         /home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar
[debug]         -classpath
[debug]         /home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/mill-build/compile-resources:/home/lefou/.cache/mill/download/0.11.0-M8:/home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/out/mill-launcher/0.11.0-M8.jar:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/mill-runner-linenumbers_2.13/0.11.0-M8/mill-runner-linenumbers_2.13-0.11.0-M8.jar:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.10/scala-compiler-2.13.10.jar:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.10/scala-reflect-2.13.10.jar:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12.jar:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.21.0/jline-3.21.0.jar:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scoverage/scalac-scoverage-runtime_2.13/2.0.8/scalac-scoverage-runtime_2.13-2.0.8.jar:/home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/ivyRepo/local/de.tototec/de.tobiasroeser.mill.vcs.version_mill0.11.0-M8_2.13/0.3.0-22-a7ac47-DIRTYb02b920b/jars/de.tobiasroeser.mill.vcs.version_mill0.11.0-M8_2.13.jar:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/mill-moduledefs_2.13/0.10.9/mill-moduledefs_2.13-0.10.9.jar:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.13/0.3.0/sourcecode_2.13-0.3.0.jar:/home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/out/mill-build/compile.dest/classes
[debug] Scala compilation took 6.811383143 s
[info] done compiling
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at mill.main.client.IsolatedMillMainLoader.runMain(IsolatedMillMainLoader.java:58)
        at mill.main.client.MillClientMain.main(MillClientMain.java:64)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
        at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
        at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
        at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
        at java.base/java.lang.reflect.Field.get(Field.java:418)
        at mill.runner.MillBuildBootstrap.getRootModule0(MillBuildBootstrap.scala:60)
        at mill.runner.MillBuildBootstrap.evaluateRec(MillBuildBootstrap.scala:92)
        at mill.runner.MillBuildBootstrap.evaluate(MillBuildBootstrap.scala:41)
        at mill.runner.MillMain$.$anonfun$main0$5(MillMain.scala:216)
        at mill.runner.Watching$.watchLoop(Watching.scala:28)
        at mill.runner.MillMain$.$anonfun$main0$1(MillMain.scala:206)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at scala.Console$.withErr(Console.scala:193)
        at mill.api.SystemStreams$.$anonfun$withStreams$2(SystemStreams.scala:56)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at scala.Console$.withOut(Console.scala:164)
        at mill.api.SystemStreams$.$anonfun$withStreams$1(SystemStreams.scala:55)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at scala.Console$.withIn(Console.scala:227)
        at mill.api.SystemStreams$.withStreams(SystemStreams.scala:54)
        at mill.runner.MillMain$.main0(MillMain.scala:80)
        at mill.runner.MillMain$.main(MillMain.scala:58)
        at mill.runner.MillMain.main(MillMain.scala)
        ... 6 more
Caused by: java.lang.NullPointerException
        at millbuild.build.<init>(build.sc:9)
        at millbuild.build$.<init>(build.sc:18)
        at millbuild.build$.<clinit>(build.sc:18)
        ... 31 more

---------- End of output
```

**Comment by lihaoyi** [comment]
Yeah, `import $exec` won't work anymore because it's an Ammonite-specific thing that relies on there being some dynamic REPL around

I'm not totally sure what you were doing in `import $exec`, but if you were setting up Mill classpaths or compiler plugins and stuff that kind of thing would now be configured in the `mill-build/build.sc`

**Comment by lefou** [comment]
In this case, `import $file` should also work, as ivy dependencies are added early. But yet it fails, probably because we no longer expose a `build` handle to the root module. That means, getting the base directory with `build.millSourcePath` no longer works.

**Comment by lefou** [comment]
I'm just adding something to the classpath with `import $ivy` which is IMHO essential to work without a `mill-build/build.sc`.

**Comment by lihaoyi** [comment]
Huh, yeah `import $ivy` is meant to work without a meta-build

**Comment by lihaoyi** [comment]
I see `build.millSourcePath` in Mill's own `build.sc`. If that no longer worked, shouldn't it fail the bootstrap tests?

**Comment by lefou** [comment]
Looks like it doesn't work when cascaded.

```
$ rg "import" *.sc
shared.sc
1:import $ivy.`org.scoverage::scalac-scoverage-runtime:2.0.8`

plugins.sc
2:import $ivy.`de.tototec:de.tobiasroeser.mill.vcs.version_mill0.11.0-M8_2.13:0.3.0-22-a7ac47-DIRTYb02b920b`

build.sc
2:import $file.plugins
4:import $file.shared
6:import de.tobiasroeser.mill.vcs.version._
7:import mill._
8:import mill.define.Command

$ cat .mill-version 
0.11.0-M8

$ mill -i resolve __
[build.sc] [17/47] unmanagedClasspath 
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at mill.main.client.IsolatedMillMainLoader.runMain(IsolatedMillMainLoader.java:58)
        at mill.main.client.MillClientMain.main(MillClientMain.java:64)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
        at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
        at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
        at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
        at java.base/java.lang.reflect.Field.get(Field.java:418)
        at mill.runner.MillBuildBootstrap.getRootModule0(MillBuildBootstrap.scala:60)
        at mill.runner.MillBuildBootstrap.evaluateRec(MillBuildBootstrap.scala:92)
        at mill.runner.MillBuildBootstrap.evaluate(MillBuildBootstrap.scala:41)
        at mill.runner.MillMain$.$anonfun$main0$5(MillMain.scala:216)
        at mill.runner.Watching$.watchLoop(Watching.scala:28)
        at mill.runner.MillMain$.$anonfun$main0$1(MillMain.scala:206)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at scala.Console$.withErr(Console.scala:193)
        at mill.api.SystemStreams$.$anonfun$withStreams$2(SystemStreams.scala:56)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at scala.Console$.withOut(Console.scala:164)
        at mill.api.SystemStreams$.$anonfun$withStreams$1(SystemStreams.scala:55)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at scala.Console$.withIn(Console.scala:227)
        at mill.api.SystemStreams$.withStreams(SystemStreams.scala:54)
        at mill.runner.MillMain$.main0(MillMain.scala:80)
        at mill.runner.MillMain$.main(MillMain.scala:58)
        at mill.runner.MillMain.main(MillMain.scala)
        ... 6 more
Caused by: java.lang.NullPointerException
        at millbuild.build.<init>(build.sc:9)
        at millbuild.build$.<init>(build.sc:18)
        at millbuild.build$.<clinit>(build.sc:18)
        ... 31 more
```

**Comment by lefou** [comment]
The import seems to work though:

``` 
$ cat out/mill-build/runClasspath.json
{
    "value": [
        "ref:v0:c984eca8:/home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/mill-build/compile-resources",
        "ref:v0:c984eca8:/home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/mill-build/resources",
        "ref:v0:cc1212cc:/home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/out/mill-build/compile.dest/classes",
        "qref:v0:2dade8ab:/home/lefou/.cache/mill/download/0.11.0-M8",
        "qref:v0:d8050954:/home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/out/mill-launcher/0.11.0-M8.jar",
        "qref:v0:eea3a350:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/mill-runner-linenumbers_2.13/0.11.0-M8/mill-runner-linenumbers_2.13-0.11.0-M8.jar",
        "qref:v0:e761310d:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.10/scala-compiler-2.13.10.jar",
        "qref:v0:a94bfc28:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar",
        "qref:v0:4baeb789:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.10/scala-reflect-2.13.10.jar",
        "qref:v0:c3fede0e:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12.jar",
        "qref:v0:ad06b5c9:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.21.0/jline-3.21.0.jar",
        "qref:v0:c30391bd:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar",
        "qref:v1:227d60af:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scoverage/scalac-scoverage-runtime_2.13/2.0.8/scalac-scoverage-runtime_2.13-2.0.8.jar",
        "qref:v1:48a67844:/home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/ivyRepo/local/de.tototec/de.tobiasroeser.mill.vcs.version_mill0.11.0-M8_2.13/0.3.0-22-a7ac47-DIRTYb02b920b/jars/de.tobiasroeser.mill.vcs.version_mill0.11.0-M8_2.13.jar",
        "qref:v1:647bb4c6:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/mill-moduledefs_2.13/0.10.9/mill-moduledefs_2.13-0.10.9.jar",
        "qref:v1:a94bfc28:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/scala-library-2.13.10.jar",
        "qref:v1:e761310d:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.10/scala-compiler-2.13.10.jar",
        "qref:v1:589290b0:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.13/0.3.0/sourcecode_2.13-0.3.0.jar",
        "qref:v1:4baeb789:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.10/scala-reflect-2.13.10.jar",
        "qref:v1:c3fede0e:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12.jar",
        "qref:v1:ad06b5c9:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.21.0/jline-3.21.0.jar",
        "qref:v1:c30391bd:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar"
    ],
    "valueHash": 453954518,
    "inputsHash": 407718548
}
```

**Comment by lefou** [comment]
Here is the generated script source: 

```
$ head -n 20 out/mill-build/generateScriptSources.dest/millbuild/build.sc 

package millbuild
import _root_.mill._
import mill.runner.MillBuildRootModule
object `MiscInfo_build`{
  implicit val millBuildRootModuleInfo: _root_.mill.runner.MillBuildRootModule.Info = _root_.mill.runner.MillBuildRootModule.Info(
    Vector("/home/lefou/.cache/mill/download/0.11.0-M8", "/home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple/out/mill-launcher/0.11.0-M8.jar").map(_root_.os.Path(_)),
    _root_.os.Path("/home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple"),
    _root_.os.Path("/home/lefou/work/opensource/mill-vcs-version/out/itest/0.11.0-M8/test.dest/01-simple")
  )
  import mill.main.TokenReaders._
  implicit val millBaseModuleInfo: _root_.mill.main.RootModule.Info = _root_.mill.main.RootModule.Info(
    millBuildRootModuleInfo.projectRoot,
    _root_.mill.define.Discover[build]
  )
}
import `MiscInfo_build`.{millBuildRootModuleInfo, millBaseModuleInfo}
object build extends build
class build extends _root_.mill.main.RootModule{

```

**Comment by lihaoyi** [comment]
@lefou IIRC `out/mill-launcher/0.11.0-M8.jar` is a copy of the mill assembly jar, and we have to copy it to a `.jar` pathname because the default download path does not end with `.jar` and the Zinc incremental compiler doesn't properly scan classpath jar files that do not have the proper extension

**Comment by lefou** [comment]
> @lefou IIRC `out/mill-launcher/0.11.0-M8.jar` is a copy of the mill assembly jar, and we have to copy it to a `.jar` pathname because the default download path does not end with `.jar` and the Zinc incremental compiler doesn't properly scan classpath jar files that do not have the proper extension

Interesting. In that case, we should no longer include the original source. But htis is probably not our issue here.

**Comment by lefou** [comment]
Todo:

* [ ] Add documentation about the unsupported `import $exec`.

**Comment by lefou** [comment]
@lihaoyi Looks like the offending line is indeed the one with the access to the top-level `build` module.

> ```scala
> val baseDir = build.millSourcePath
> ```

Turns out, making it a `def` fixes the issue. This is probably some Scala specific too early access to a `val` issue. And the error message is not helpful either.

**Comment by lihaoyi** [comment]
Hah Scala initialization order strikes again

**Comment by lefou** [comment]
> Hah Scala initialization order strikes again

Exactly. Because we mix traits, we definitely raised the probability for users to run into this. The `val baseDir` worked previously. Maybe, we could catch the `ExceptionInInitializerError` and provide some hints / guidance what to look for.

**Comment by lefou** [comment]
* I have a follow up issue, but only on Windows: #2468
