### ISSUE TITLE
Import ivy statement breaking on version 0.11-M8

### ISSUE THREAD

**Issue by Naum-Tomov** [com-lihaoyi/mill#2526]
I am trying to bump the mill version of a project and noticed that this import statement, which previously worked:
```
import $ivy.`com.lihaoyi::mill-contrib-scalapblib:`
```
breaks the compilation of my project with the following error message:
```
Exception in thread "MillServerActionRunner" java.lang.Exception: Duplicated item inserted into OrderedSet: Failure(
Resolution failed for 1 modules:
--------------------------------------------
  com.lihaoyi::mill-contrib-buildinfo 
    not found: /Users/naum/.ivy2/local/com.lihaoyi/mill-contrib-buildinfo/ivys/ivy.xml
    not found: https://repo1.maven.org/maven2/com/lihaoyi//mill-contrib-buildinfo/-mill-contrib-buildinfo.pom
--------------------------------------------

For additional information on library dependencies, see the docs at
https://com-lihaoyi.github.io/mill/mill/Library_Dependencies.html
,None)
      at mill.api.AggWrapper$Agg$Mutable.append(AggWrapper.scala:63)
      at mill.util.MultiBiMap$Mutable.add(MultiBiMap.scala:38)
      at mill.util.MultiBiMap$Mutable.$anonfun$addAll$1(MultiBiMap.scala:47)
      at mill.util.MultiBiMap$Mutable.$anonfun$addAll$1$adapted(MultiBiMap.scala:47)
      at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
      at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
      at scala.collection.AbstractIterator.foreach(Iterator.scala:1300)
      at mill.util.MultiBiMap$Mutable.addAll(MultiBiMap.scala:47)
      at mill.eval.Evaluator.$anonfun$getFailing$2(Evaluator.scala:185)
      at mill.eval.Evaluator.$anonfun$getFailing$2$adapted(Evaluator.scala:182)
      at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:575)
      at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:573)
      at scala.collection.AbstractIterator.foreach(Iterator.scala:1300)
      at mill.eval.Evaluator.getFailing(Evaluator.scala:182)
      at mill.eval.Evaluator.$anonfun$sequentialEvaluate$1(Evaluator.scala:172)
      at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
      at mill.eval.Evaluator.sequentialEvaluate(Evaluator.scala:121)
      at mill.eval.Evaluator.evaluate(Evaluator.scala:112)
      at mill.main.RunScript$.evaluateNamed(RunScript.scala:167)
      at mill.main.RunScript$.evaluate(RunScript.scala:153)
      at mill.main.RunScript$.$anonfun$evaluateTasks$1(RunScript.scala:118)
      at scala.util.Either.map(Either.scala:382)
      at mill.main.RunScript$.evaluateTasks(RunScript.scala:116)
      at mill.runner.MillBuildBootstrap$.evaluateWithWatches(MillBuildBootstrap.scala:336)
      at mill.runner.MillBuildBootstrap.processRunClasspath(MillBuildBootstrap.scala:180)
      at mill.runner.MillBuildBootstrap.evaluateRec(MillBuildBootstrap.scala:150)
      at mill.runner.MillBuildBootstrap.evaluateRec(MillBuildBootstrap.scala:84)
      at mill.runner.MillBuildBootstrap.evaluate(MillBuildBootstrap.scala:41)
      at mill.runner.MillMain$.$anonfun$main0$5(MillMain.scala:216)
```

This issue does not occur with version 11-M7. The `-j 0` option has *no* affect on the bug.

**Comment by lihaoyi** [comment]
This should be fixed by https://github.com/com-lihaoyi/mill/pull/2476, which will go out as part of the next milestone 0.11.0-M9. Hopefully soon-ish
