### ISSUE TITLE
Randomly ConcurrentModificationException

### ISSUE THREAD

**Issue by jilen** [com-lihaoyi/mill#2540]
Version : 0.11.0-M9
Sometimes ConcurrentModificationException will be thrown while runing `mill -j N __.compile`
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at mill.main.client.IsolatedMillMainLoader.runMain(IsolatedMillMainLoader.java:58)
	at mill.main.client.MillClientMain.main(MillClientMain.java:64)
Caused by: java.util.ConcurrentModificationException: mutation occurred during iteration
	at scala.collection.mutable.MutationTracker$.checkMutations(MutationTracker.scala:43)
	at scala.collection.mutable.CheckedIndexedSeqView$CheckedIterator.hasNext(CheckedIndexedSeqView.scala:47)
	at scala.collection.immutable.List.prependedAll(List.scala:155)
	at scala.collection.immutable.List$.from(List.scala:684)
	at scala.collection.immutable.List$.from(List.scala:681)
	at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
	at scala.collection.immutable.Seq$.from(Seq.scala:42)
	at scala.collection.IterableOnceOps.toSeq(IterableOnce.scala:1300)
	at scala.collection.IterableOnceOps.toSeq$(IterableOnce.scala:1300)
	at scala.collection.AbstractIterable.toSeq(Iterable.scala:933)
	at mill.eval.EvaluatorImpl.evaluate0(EvaluatorImpl.scala:170)
	at mill.eval.EvaluatorImpl.$anonfun$evaluate$1(EvaluatorImpl.scala:78)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at mill.eval.EvaluatorImpl.evaluate(EvaluatorImpl.scala:69)
	at mill.main.RunScript$.evaluateNamed(RunScript.scala:39)
	at mill.main.RunScript$.$anonfun$evaluateTasksNamed$2(RunScript.scala:27)
	at scala.util.Either.map(Either.scala:382)
	at mill.main.RunScript$.evaluateTasksNamed(RunScript.scala:26)
	at mill.runner.MillBuildBootstrap$.evaluateWithWatches(MillBuildBootstrap.scala:325)
	at mill.runner.MillBuildBootstrap.processFinalTargets(MillBuildBootstrap.scala:246)
	at mill.runner.MillBuildBootstrap.evaluateRec(MillBuildBootstrap.scala:144)
	at mill.runner.MillBuildBootstrap.evaluate(MillBuildBootstrap.scala:44)
	at mill.runner.MillMain$.$anonfun$main0$5(MillMain.scala:222)
	at mill.runner.Watching$.watchLoop(Watching.scala:27)
	at mill.runner.MillMain$.$anonfun$main0$1(MillMain.scala:210)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withErr(Console.scala:193)
	at mill.api.SystemStreams$.$anonfun$withStreams$2(SystemStreams.scala:56)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withOut(Console.scala:164)
	at mill.api.SystemStreams$.$anonfun$withStreams$1(SystemStreams.scala:55)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withIn(Console.scala:227)
	at mill.api.SystemStreams$.withStreams(SystemStreams.scala:54)
	at mill.runner.MillMain$.main0(MillMain.scala:80)
	at mill.runner.MillMain$.main(MillMain.scala:58)
	at mill.runner.MillMain.main(MillMain.scala)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
```

**Comment by lefou** [comment]
@jilen Thank you for testing Mill milestones and reporting issues!
