### ISSUE TITLE
`[error] class type required but {some traits} found _root_.mill.define.Discover[build]`

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#2579]
## Issue

With Mill `0.11.0` and `0.11.0-M11` I see the following error message when using the scoverage contrib module:

```
[error] /tmp/out/mill-build/generateScriptSources.dest/millbuild/build.sc:14:32: class type required but mill.define.Module.BaseClass with ScoverageModule.this.ScoverageData found
[error]     _root_.mill.define.Discover[build]
[error]                                ^
```

## Real World Projects

* Initial discovered in https://github.com/lefou/mill-vcs-version/pull/121
* Also in https://github.com/lefou/mill-integrationtest/pull/164

## Minimized Reproduction

```scala
import $ivy.`com.lihaoyi::mill-contrib-scoverage:`
import mill._
import mill.contrib.scoverage.ScoverageModule
import mill.scalalib._

object core extends Cross[CoreCross]("2.13.11")
trait CoreCross extends CrossScalaModule with ScoverageModule {
  override def scoverageVersion = "2.0.10"
}
```

```
$ mill __.compile
Using mill version 0.11.0-M11
[build.sc] [41/49] compile 
[info] compiling 1 Scala source to /home/lefou/work/opensource/mill-vcs-version/repro-discover-issue/out/mill-build/compile.dest/classes ...
[error] /home/lefou/work/opensource/mill-vcs-version/repro-discover-issue/out/mill-build/generateScriptSources.dest/millbuild/build.sc:14:32: class type required but mill.define.Module.BaseClass with ScoverageModule.this.ScoverageData found
[error]     _root_.mill.define.Discover[build]
[error]                                ^
[error] one error found
1 targets failed
compile Compilation failed
```

```scala
$ cat out/mill-build/generateScriptSources.dest/millbuild/build.sc 

package millbuild
import _root_.mill._
import mill.runner.MillBuildRootModule
object MiscInfo_build{
  implicit val millBuildRootModuleInfo: _root_.mill.runner.MillBuildRootModule.Info = _root_.mill.runner.MillBuildRootModule.Info(
    Vector("/home/lefou/.cache/mill/download/0.11.0-M11", "/home/lefou/work/opensource/mill-vcs-version/repro-discover-issue/out/mill-launcher/0.11.0-M11.jar").map(_root_.os.Path(_)),
    _root_.os.Path("/home/lefou/work/opensource/mill-vcs-version/repro-discover-issue"),
    _root_.os.Path("/home/lefou/work/opensource/mill-vcs-version/repro-discover-issue"),
    _root_.scala.Seq()
  )
  implicit val millBaseModuleInfo: _root_.mill.main.RootModule.Info = _root_.mill.main.RootModule.Info(
    millBuildRootModuleInfo.projectRoot,
    _root_.mill.define.Discover[build]
  )
}
import MiscInfo_build.{millBuildRootModuleInfo, millBaseModuleInfo}
object build extends build
class build extends _root_.mill.main.RootModule{

//MILL_ORIGINAL_FILE_PATH=/home/lefou/work/opensource/mill-vcs-version/repro-discover-issue/build.sc
//MILL_USER_CODE_START_MARKER
import _root_._
import mill._
import mill.contrib.scoverage.ScoverageModule
import mill.scalalib._

object core extends Cross[CoreCross]("2.13.11")
trait CoreCross extends CrossScalaModule with ScoverageModule {
  override def scoverageVersion = "2.0.10"
}
```

**Comment by lihaoyi** [comment]
This guy here needs a type annotation for `: ScoverageData`, to prevent Scalac from inferring a weird type for the anonymous that breaks things:

- https://github.com/com-lihaoyi/mill/blob/main/contrib/scoverage/src/mill/contrib/scoverage/ScoverageModule.scala#L175

Not sure why it didn't get caught in CI; maybe no tests exercised it?

This is definitely a bit of a footgun, but I'm not sure what can be done about it. Maybe a macro that does this up-casting would help?

**Comment by lefou** [comment]
Maybe, we can enable more linting so we end up with more warnings/errors about missing type annotations for public `val`s/`def`s?

**Comment by lefou** [comment]
Thanks for the quick analysis, @lihaoyi .

**Comment by lihaoyi** [comment]
As a workaround, does `override lazy val scoverage: = super.scoverage` work?

**Comment by lefou** [comment]
> override lazy val scoverage: = super.scoverage

Unfortunately not. 

`super may not be used on lazy value scoverage; super can only be used to select a member that is a method or type`

**Comment by lihaoyi** [comment]
How about `override lazy val scoverage: ScoverageData =  new ScoverageData {}`?

**Comment by lefou** [comment]
But this works:

```scala
override lazy val scoverage: ScoverageData = new ScoverageData {}
```

**Comment by lefou** [comment]
You can use the latest snapshot builds which already contain the fix. The latest available snapshot is currently `0.11.0-21-02e278`.

**Comment by urbanchr** [comment]
I am running 0.11.1 but unfortunately I still receive this error (see below). Christian



Exception in thread "MillServerActionRunner" java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1113)
	at java.base/java.lang.reflect.Field.get(Field.java:425)
	at mill.runner.MillBuildBootstrap$.getRootModule(MillBuildBootstrap.scala:347)
	at mill.runner.MillBuildBootstrap.evaluateRec(MillBuildBootstrap.scala:106)
	at mill.runner.MillBuildBootstrap.evaluate(MillBuildBootstrap.scala:45)
	at mill.runner.MillMain$.$anonfun$main0$5(MillMain.scala:205)
	at mill.runner.Watching$.watchLoop(Watching.scala:27)
	at mill.runner.MillMain$.$anonfun$main0$1(MillMain.scala:193)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withErr(Console.scala:193)
	at mill.api.SystemStreams$.$anonfun$withStreams$2(SystemStreams.scala:56)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withOut(Console.scala:164)
	at mill.api.SystemStreams$.$anonfun$withStreams$1(SystemStreams.scala:55)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withIn(Console.scala:227)
	at mill.api.SystemStreams$.withStreams(SystemStreams.scala:54)
	at mill.runner.MillMain$.main0(MillMain.scala:80)
	at mill.runner.MillServerMain$.main0(MillServerMain.scala:83)
	at mill.runner.MillServerMain$.main0(MillServerMain.scala:35)
	at mill.runner.Server.$anonfun$handleRun$1(MillServerMain.scala:186)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "millbuild.build$.millSourcePath()" because "millbuild.build$.MODULE$" is null
	at millbuild.build.<init>(build.sc:4)
	at millbuild.build$.<init>(build.sc:18)
	at millbuild.build$.<clinit>(build.sc:18)

**Comment by lefou** [comment]
@urbanchr Your issue is unrelated. I think a fix is avoid to capture the value of `build.moduleSourcePath` in a `val` by using a `def` or `lazy val`.
