### ISSUE TITLE
Exception in thread "MillServerActionRunner" `java.lang.ExceptionInInitializerError`

### ISSUE THREAD

**Issue by lefou** [com-lihaoyi/mill#2582]
Mill 0.11.0

Project: https://github.com/lefou/mill-vcs-version/commit/d09eb3d9e5acd573c59ca08a6fd7d5b351118293

```
$ mill -j 0 __.compile + __.testCached
[build.sc] [#00] [22/49] cliImports 
Exception in thread "MillServerActionRunner" java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
        at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
        at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
        at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
        at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
        at java.base/java.lang.reflect.Field.get(Field.java:418)
        at mill.runner.MillBuildBootstrap$.getRootModule(MillBuildBootstrap.scala:347)
        at mill.runner.MillBuildBootstrap.evaluateRec(MillBuildBootstrap.scala:106)
        at mill.runner.MillBuildBootstrap.evaluate(MillBuildBootstrap.scala:45)
        at mill.runner.MillMain$.$anonfun$main0$5(MillMain.scala:222)
        at mill.runner.Watching$.watchLoop(Watching.scala:27)
        at mill.runner.MillMain$.$anonfun$main0$1(MillMain.scala:210)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at scala.Console$.withErr(Console.scala:193)
        at mill.api.SystemStreams$.$anonfun$withStreams$2(SystemStreams.scala:56)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at scala.Console$.withOut(Console.scala:164)
        at mill.api.SystemStreams$.$anonfun$withStreams$1(SystemStreams.scala:55)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at scala.Console$.withIn(Console.scala:227)
        at mill.api.SystemStreams$.withStreams(SystemStreams.scala:54)
        at mill.runner.MillMain$.main0(MillMain.scala:80)
        at mill.runner.MillServerMain$.main0(MillServerMain.scala:83)
        at mill.runner.MillServerMain$.main0(MillServerMain.scala:35)
        at mill.runner.Server.$anonfun$handleRun$1(MillServerMain.scala:186)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
        at millbuild.build.<init>(build.sc:18)
        at millbuild.build$.<init>(build.sc:18)
        at millbuild.build$.<clinit>(build.sc:18)
        ... 27 more
```

```scala
$ head -n 20 out/mill-build/generateScriptSources.dest/millbuild/build.sc
package millbuild

import _root_.mill.runner.MillBuildRootModule

object MiscInfo_build {
  implicit val millBuildRootModuleInfo: _root_.mill.runner.MillBuildRootModule.Info = _root_.mill.runner.MillBuildRootModule.Info(
    Vector("/home/lefou/.cache/mill/download/0.11.0", "/home/lefou/work/opensource/mill-vcs-version/out/mill-launcher/0.11.0.jar").map(_root_.os.Path(_)),
    _root_.os.Path("/home/lefou/work/opensource/mill-vcs-version"),
    _root_.os.Path("/home/lefou/work/opensource/mill-vcs-version"),
    _root_.scala.Seq()
  )
  implicit val millBaseModuleInfo: _root_.mill.main.RootModule.Info = _root_.mill.main.RootModule.Info(
    millBuildRootModuleInfo.projectRoot,
    _root_.mill.define.Discover[build]
  )
}
import MiscInfo_build.{millBuildRootModuleInfo, millBaseModuleInfo}
object build extends build
class build extends _root_.mill.main.RootModule {

```

**Comment by lefou** [comment]
Probably related to #2579, so maybe an issue with Scala initialization order.

**Comment by lefou** [comment]
The issue is the top-level `val` accessing the inherited class/trait. Essentially the `val` gets initialized before the right-hand side. This can be worked around with a `lazy val` or `def`.
