### ISSUE TITLE
Exception when running tests using ScalaTest

### ISSUE THREAD

**Issue by ex0ns** [com-lihaoyi/mill#2595]
When upgrading to mill 0.11.0 I got the following stack trace when trying to run my tests using scalatest

```
ex0ns@build:~/tmp$ mill  __.test
[82/83] core.test.test.super.mill.scalalib.TestModule.test 
java.lang.NoClassDefFoundError: sbt/testing/EventHandler
java.lang.NoClassDefFoundError: sbt/testing/EventHandler
        at mill.testrunner.TestRunnerMain0$.main0(TestRunnerMain0.scala:29)
        at mill.testrunner.TestRunnerMain0.main0(TestRunnerMain0.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at mill.testrunner.entrypoint.TestRunnerMain.main(TestRunnerMain.java:41)
Caused by: java.lang.ClassNotFoundException: sbt.testing.EventHandler
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at mill.testrunner.entrypoint.TestRunnerMain$1.findClass(TestRunnerMain.java:30)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 7 more
```

The minimized `build.sc`:
```scala
import mill._
import mill.scalalib._

object library {

  object Version {
    val scalaTest  = "3.2.16"
    val sbtTesting = "1.0"
  }

  val scalaTest  = ivy"org.scalatest::scalatest::${Version.scalaTest}"
  val sbtTesting = ivy"org.scala-sbt:test-interface:${Version.sbtTesting}"
}

object core extends ScalaModule {
  def scalaVersion = "2.13.11"

  object test extends ScalaTests with TestModule.ScalaTest {
    def ivyDeps = T {
      super.ivyDeps() ++ Agg(
        library.scalaTest
          // library.sbtTesting
      )
    }
  }
}
```

Adding  `test-interface` explicitly fixes the issue, but I think that there must be something else going on here

**Comment by lolgab** [comment]
It seems that there is a problem resolving transitive dependencies.
Since `scalatest` depends on `scalatest-core` which depends on `test-interface` already.
https://central.sonatype.com/artifact/org.scalatest/scalatest-core_2.13/3.2.16/dependencies

**Comment by ex0ns** [comment]
Side note (and probably expected), I get the exact same issue with a project running zio-test

**Comment by lefou** [comment]
Thanks for your report! This looks like a bug in Mill to me. We changed the way how we run tests and test frameworks. Instead of loading the test into a mostly isolated classloader hierarchy below the test runner, we now load the test runner into the tests class path. I guess, we might have overlooked something and need some more tweaking.

* https://github.com/com-lihaoyi/mill/pull/2561

**Comment by lihaoyi** [comment]
Yeah, that change aimed to run the tests in as clean a classpath as possible. Maybe we need to add `org.scala-sbt:test-interface` to `TestModule.ScalaTest` by default? From @lolgab's link, it seems like `org.scala-sbt:test-interface` should get pulled in automatically, but we must be missing something

**Comment by lefou** [comment]
As we clearly depend on test-interface, we should always add this dependency to the run classpath, when resolving the test runner.

**Comment by ex0ns** [comment]
I don't think  I will have the time to contribute before the end of the week, however where would be the best place to include that ?
If I understood the problem correctly, we would need the `runClasspath` located https://github.com/com-lihaoyi/mill/blob/e5a39907b04ecaf93a4736108426afca0a0abe75/scalalib/src/mill/scalalib/TestModule.scala#L126 to contain org.scala-sbt:test-interface is that the correct idea ?

**Comment by lihaoyi** [comment]
If it's the Mill code in TestRunnetMain0 that depends on test-interface, shouldnt we just add the dependency to thay module in https://github.com/com-lihaoyi/mill/blob/e5a39907b04ecaf93a4736108426afca0a0abe75/build.sc#L511?

**Comment by lefou** [comment]
We should! (I was not sure whether our module loading mechanism can do that.)

**Comment by lefou** [comment]
Probably, because the dependency is marked as optional. We should have a test case for each supported test framework.

**Comment by ex0ns** [comment]
So, a bit of news, I got some time to (try) adding tests for that, see https://github.com/com-lihaoyi/mill/pull/2609 

Also, regarding @lihaoyi comments about the `testrunner` it seems that this is not the issue here (unless it was fix in between):

```
ex0ns@build:~/Projects/mill$ mill show testrunner.runClasspath | grep test-interface
[info] compiling 1 Scala source to /home/ex0ns/Projects/mill/out/mill-build/compile.dest/classes ...
[info] done compiling
  "qref:v1:3ed2ed17:/home/ex0ns/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar",
  ```
  
  The jar is already in the class path for this
  
Do the tests looks good ? Should I continue with other tests framework  ? I have added the libraries in the main `build.sc` so we get update when there is a new version of the test framework, is it a good idea or should we hardcode the values in the tests ?

**Comment by lihaoyi** [comment]
@ex0ns interesting. If the class is actually on the classpath, then the problem may well be on this line where we try and splice the classpaths together https://github.com/com-lihaoyi/mill/blob/main/testrunner/entrypoint/src/mill/testrunner/entrypoint/TestRunnerMain.java#L29

**Comment by ex0ns** [comment]
I am not sure that I fully understand, are you talking about something like that:

```java
if (name.startsWith("sbt.testing")) {
  try {
    return TestRunnerMain.class.getClassLoader().loadClass(name);
   catch (ClassNotFoundException e) {
     return super.findClass(name);
    }
 } else {
```

If yes, then we still have an issue, the stack trace went from:

```
java.lang.NoClassDefFoundError: sbt/testing/EventHandler
java.lang.NoClassDefFoundError: sbt/testing/EventHandler
        at mill.testrunner.TestRunnerMain0$.main0(TestRunnerMain0.scala:29)
        at mill.testrunner.TestRunnerMain0.main0(TestRunnerMain0.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at mill.testrunner.entrypoint.TestRunnerMain.main(TestRunnerMain.java:55)
Caused by: java.lang.ClassNotFoundException: sbt.testing.EventHandler
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at mill.testrunner.entrypoint.TestRunnerMain$1.findClass(TestRunnerMain.java:34)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 7 more
``` 
Failing in `      val filter = TestRunnerUtils.globFilter(testArgs.globSelectors)`

With this try/catch, the stack trace become:

```
java.lang.NoClassDefFoundError: sbt/testing/Framework
java.lang.NoClassDefFoundError: sbt/testing/Framework
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at mill.testrunner.Framework$.framework(Framework.scala:9)
        at mill.testrunner.TestRunnerMain0$.$anonfun$main0$2(TestRunnerMain0.scala:33)
        at mill.testrunner.TestRunnerUtils$.runTestFramework0(TestRunnerUtils.scala:109)
        at mill.testrunner.TestRunnerMain0$.main0(TestRunnerMain0.scala:39)
        at mill.testrunner.TestRunnerMain0.main0(TestRunnerMain0.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at mill.testrunner.entrypoint.TestRunnerMain.main(TestRunnerMain.java:48)
Caused by: java.lang.ClassNotFoundException: sbt.testing.Framework
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 19 morejava.lang.NoClassDefFoundError: sbt/testing/Framework
java.lang.NoClassDefFoundError: sbt/testing/Framework
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at mill.testrunner.Framework$.framework(Framework.scala:9)
        at mill.testrunner.TestRunnerMain0$.$anonfun$main0$2(TestRunnerMain0.scala:33)
        at mill.testrunner.TestRunnerUtils$.runTestFramework0(TestRunnerUtils.scala:109)
        at mill.testrunner.TestRunnerMain0$.main0(TestRunnerMain0.scala:39)
        at mill.testrunner.TestRunnerMain0.main0(TestRunnerMain0.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at mill.testrunner.entrypoint.TestRunnerMain.main(TestRunnerMain.java:48)
Caused by: java.lang.ClassNotFoundException: sbt.testing.Framework
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 19 mor
```


Which is a failure inside `TestRunnerUtils`, when loading the framework
```scala
    val framework = frameworkInstances(cl)
```

**Comment by lihaoyi** [comment]
So with the try catch, even though the immediate failure goes away, we still have a failure later on. This is because the child classloader uses the parent classloader when trying to load the `sbt.testing.Framework` instances. This makes sense. And because the parent classloader does not have `sbt.testing.*` on the classpath, this fails.

I think we have no choice but to either add the `test-interface` dependency to `testrunner.entrypoint`, or add it to each of `TestModule.ScalaTest`, `TestModule.ZIOTest`, etc that seem to have the dependency marked as optional.

**Comment by lefou** [comment]
> So with the try catch, even though the immediate failure goes away, we still have a failure later on. This is because the child classloader uses the parent classloader when trying to load the `sbt.testing.Framework` instances. This makes sense, as test frameworks are defined in the user classpath or even user code. And because the parent classloader does not have `sbt.testing.*` on the classpath, this fails.
> 
> I think we have no choice but to either add the `test-interface` dependency to `testrunner.entrypoint`, or add it to each of `TestModule.ScalaTest`, `TestModule.ZIOTest`, etc. that seem to have the dependency marked as optional. I don't have a strong opinion here which one is better, so either works for me

I'd prefer to add it to `testrunner.entrypoint`, as `runIvyDeps` if possible, or as `ivyDeps` otherwise. The reason is, that the customized classloading is located in this project and explicitly requests it's own classloader, so this project clearly requires this dependency at runtime.

**Comment by lolgab** [comment]
Also you can use scalatest by simply setting the `def testFramework` and only adding the dependency in `TestModule.Scalatest` would not fix the problem in this case.

**Comment by lefou** [comment]
```
[info] compiling 1 Scala source to /home/lefou/work/opensource/mill/target/workspace/mill/scalalib/TestRunnerTests/eval/TestRunner/ZioTest/ziotest.test/ziotest/compile.dest/classes ...
mill.scalalib.TestRunnerTests: [83/83] ziotest.test 
java.lang.ClassNotFoundException: zio.test.sbt.ZTestFramework
java.lang.ClassNotFoundException: zio.test.sbt.ZTestFramework
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at mill.testrunner.Framework$.framework(Framework.scala:9)
        at mill.testrunner.TestRunnerMain0$.$anonfun$main0$2(TestRunnerMain0.scala:32)
        at mill.testrunner.TestRunnerUtils$.runTestFramework0(TestRunnerUtils.scala:109)
        at mill.testrunner.TestRunnerMain0$.main0(TestRunnerMain0.scala:38)
        at mill.testrunner.TestRunnerMain0.main0(TestRunnerMain0.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at mill.testrunner.entrypoint.TestRunnerMain.main(TestRunnerMain.java:42)
mill.scalalib.TestRunnerTests: [83/83] ziotest.test failed
X mill.scalalib.TestRunnerTests.TestRunner.ZioTest.ziotest.test 5377ms 
  scala.MatchError: Left(Failure(Test execution failed.,None)) (of class scala.util.Left)
    mill.scalalib.TestRunnerTests$.$anonfun$tests$23(TestRunnerTests.scala:102)
    mill.scalalib.TestRunnerTests$.$anonfun$tests$23$adapted(TestRunnerTests.scala:101)
    mill.scalalib.TestRunnerTests$.workspaceTest(TestRunnerTests.scala:53)
    mill.scalalib.TestRunnerTests$.$anonfun$tests$22(TestRunnerTests.scala:56)
1 targets failed
scalalib.test.testOnly 1 tests failed: 
  mill.scalalib.TestRunnerTests mill.scalalib.TestRunnerTests.TestRunner.ZioTest.ziotest.test
```

**Comment by lefou** [comment]
Looks like an additional artifact `zio-test-sbt` is needed.

**Comment by ex0ns** [comment]
oh you are correct, and this is documented on ZIO's side it seems: https://zio.dev/reference/test/installation so  I guess we don't have to do anything specific about that (except what you did to fix the tests in the PR)

**Comment by lefou** [comment]
I still see the same issue although I use the latest Mill snapshot release containing the fix.

https://github.com/lefou/mill-kotlin/actions/runs/5298466073/jobs/9590834819?pr=80

```
 java.lang.NoClassDefFoundError: sbt/testing/EventHandler
java.lang.NoClassDefFoundError: sbt/testing/EventHandler
	at mill.testrunner.TestRunnerMain0$.main0(TestRunnerMain0.scala:29)
	at mill.testrunner.TestRunnerMain0.main0(TestRunnerMain0.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at mill.testrunner.entrypoint.TestRunnerMain.main(TestRunnerMain.java:42)
Caused by: java.lang.ClassNotFoundException: sbt.testing.EventHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at mill.testrunner.entrypoint.TestRunnerMain$1.findClass(TestRunnerMain.java:31)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
1 targets failed
main[0.10].test.test Test execution failed.
```

What am I missing. This is a scoverage enabled test module, so it could be relevant.

**Comment by lolgab** [comment]
You are probably missing `super.ivyDeps() ++` in https://github.com/lefou/mill-kotlin/blob/a553c6acaa4a7e9e100c162e84b756094ebede69/build.sc#L143
Should we use `mandatoryIvyDeps` for `test-interface` to avoid this problem?

**Comment by lefou** [comment]
I don't think that's the issue, as we always add the entrypoint classpath. https://github.com/com-lihaoyi/mill/blob/a9e453d7ff203eb3909ea2bf92f070418a7985b2/scalalib/src/mill/scalalib/TestModule.scala#L127

**Comment by lefou** [comment]
But I currently wonder, whether there is a difference regarding the runtime-dependency handling from within Mill tests vs. when running standalone.

**Comment by lefou** [comment]
Yeah, looks like that makes the difference.
