### ISSUE TITLE
`-i/--interactive` not working

### ISSUE THREAD

**Issue by jilen** [com-lihaoyi/mill#2704]
When run `mill -i xxx.console`
It create a dumb terminal

```
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
```

**Comment by lefou** [comment]
I can reproduce with Mill version `0.11.1-33-6635d2`

**Comment by philwalk** [comment]
Not sure if it's related, but I'm seeing system terminal crash while working with `scala-cli`:
```
Launching Mill as sub-process ...
Publishing Artifact(org.virtuslab.scala-cli,runner_3,1.0.5-SNAPSHOT) to ivy repo C:\Users\philwalk\workspace\scala-cli\out\repo\1.0.5-SNAPSHOT
Publishing Artifact(org.virtuslab.scala-cli,test-runner_3,1.0.5-SNAPSHOT) to ivy repo C:\Users\philwalk\workspace\scala-cli\out\repo\1.0.5-SNAPSHOT
Publishing Artifact(org.virtuslab.scala-cli,runner_2.13,1.0.5-SNAPSHOT) to ivy repo C:\Users\philwalk\workspace\scala-cli\out\repo\1.0.5-SNAPSHOT
Publishing Artifact(org.virtuslab.scala-cli,test-runner_2.13,1.0.5-SNAPSHOT) to ivy repo C:\Users\philwalk\workspace\scala-cli\out\repo\1.0.5-SNAPSHOT
Publishing Artifact(org.virtuslab.scala-cli,runner_2.12,1.0.5-SNAPSHOT) to ivy repo C:\Users\philwalk\workspace\scala-cli\out\repo\1.0.5-SNAPSHOT
Publishing Artifact(org.virtuslab.scala-cli,test-runner_2.12,1.0.5-SNAPSHOT) to ivy repo C:\Users\philwalk\workspace\scala-cli\out\repo\1.0.5-SNAPSHOT
Exception in thread "main" java.lang.IllegalStateException: Unable to create a system terminal
        at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:323)
        at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:265)
        at dotty.tools.repl.JLineTerminal.<init>(JLineTerminal.scala:23)
        at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:136)
        at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:127)
        at dotty.tools.repl.Main$.main(Main.scala:6)
        at dotty.tools.repl.Main.main(Main.scala)
1 targets failed
cli.console java.lang.Exception: Interactive Subprocess Failed (exit code 1)
    mill.util.Jvm$.runSubprocess(Jvm.scala:143)
    mill.util.Jvm$.runSubprocess(Jvm.scala:116)
    mill.scalalib.ScalaModule.$anonfun$console$1(ScalaModule.scala:370)
    mill.define.Task$TraverseCtx.evaluate(Task.scala:71)
```
I captured the `--debug` output of the command and examined the last subprocess command line.
```sh
mill --debug -i cli.console 2>&1 |  grep 'Run subprocess' | tail -1 | sed -e 's/Run subprocess with args: //' | tr -d '\r' | tee  cliConsole.out 
```
The resulting command line looks like this (classpath separated for clarity):
```sh
CP='blah-blah-blah`
C:/opt/jdk/bin/java.exe -cp "$CP" 'dotty.tools.repl.Main -usejavacp
```
When I issue the subprocess command line, the error (`Unable to create a system terminal`) doesn't occur:
```
$ bash cliConsole.out
Welcome to Scala 3.1.2 (17.0.2, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> 
```

One possible explanation is that the problem happens because `jline3` is unhappy with environment variables.
Several variables are referenced in `jline3` code.

Here are the values in various build environments, all of which successfully create a terminal:
```
MINGW64_NT-10.0-22621 d5 3.4.7.x86_64 2023-08-09 17:32 UTC x86_64 Msys
ConEmuPID         : []
IDE_HOME          : []
INSIDE_EMACS      : []
MSYSTEM           : [MINGW64]
OSTYPE            : [msys]
PWD               : [/Users/philwalk/workspace/jline3]
TERM              : [xterm-256color]
WSL_DISTRO_NAME   : []
WSL_INTEROP       : []
```
```
CYGWIN_NT-10.0-22621 d5 3.4.8-1.x86_64 2023-08-17 17:02 UTC x86_64 Cygwin
ConEmuPID         : []
IDE_HOME          : []
INSIDE_EMACS      : []
MSYSTEM           : []
OSTYPE            : [cygwin]
PWD               : [/home/philwalk/workspace/scala-cli]
TERM              : [xterm]
WSL_DISTRO_NAME   : []
WSL_INTEROP       : []
```
```
Linux d5 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
ConEmuPID         : []
IDE_HOME          : []
INSIDE_EMACS      : []
MSYSTEM           : []
OSTYPE            : [linux-gnu]
PWD               : [/mnt/c/Users/philwalk/workspace/scala-cli]
TERM              : [xterm-256color]
WSL_DISTRO_NAME   : [Ubuntu]
WSL_INTEROP       : [/run/WSL/29966_interop]
```
```
rem CMD.EXE
ConEmuPID         : []
IDE_HOME          : []
INSIDE_EMACS      : []
MSYSTEM           : []
OSTYPE            : []
PWD               : []
TERM              : []
WSL_DISTRO_NAME   : []
WSL_INTEROP       : []
```

**Comment by lefou** [comment]
This was introduced between `0.11.0-M7` and `0.11.0-M8`.

```scala
// build.sc
import mill._, scalalib._

object foo extends ScalaModule {
  def scalaVersion = "2.13.11"
}
```

```
$ MILL_VERSION="0.11.0-M7" mill -i foo.console
[44/44] foo.console 
Welcome to Scala 2.13.11 (OpenJDK 64-Bit Server VM, Java 11.0.18).
Type in expressions for evaluation. Or try :help.

scala> 
:quit
```

```
$ MILL_VERSION="0.11.0-M8" mill -i foo.console
[44/44] foo.console 
Welcome to Scala 2.13.11 (OpenJDK 64-Bit Server VM, Java 11.0.18).
Type in expressions for evaluation. Or try :help.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jline.terminal.impl.exec.ExecTerminalProvider (file:/home/lefou/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.22.0/jline-3.22.0.jar) to constructor java.lang.ProcessBuilder$RedirectPipeImpl()
WARNING: Please consider reporting this to the maintainers of org.jline.terminal.impl.exec.ExecTerminalProvider
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Sep. 05, 2023 12:45:28 NACHM. org.jline.utils.Log logr
WARNUNG: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)

scala> ^C
```

**Comment by lihaoyi** [comment]
Seems this was introduced in 9ff2e8f2eaeffb0d7dc69a83fb65db264ce37373
