### ISSUE TITLE
Repro for Duplicated item inserted into OrderedSet

### ISSUE THREAD

**Issue by Quafadas** [com-lihaoyi/mill#2958]
@lefou  Aha! I believe I have a semi-minimal reproduction for this on a public repository. 

1. `git clone https://github.com/Quafadas/vecxt.git`
2. To prove that main works (you don't need to do this)
   *  `mill -j 1 vecxt.jvm.prepareOffline`
3. `git checkout build_error`
4.  `mill clean`
5.  `mill -j 1 vecxt.jvm.prepareOffline`

The first time I do this, I get 

```
simon@Simons-Mac-mini vecxt % mill clean
[1/1] clean 
simon@Simons-Mac-mini vecxt % mill -j 1 vecxt.jvm.prepareOffline
[23/23] vecxt.jvm.prepareOffline 
An unexpected error occurred
Exception in thread "MillServerActionRunner" java.lang.Exception: Duplicated item inserted into OrderedSet: mill.define.Task$TraverseCtx@630efd4
        at mill.api.AggWrapper$Agg$Mutable.append(AggWrapper.scala:99)
        at mill.api.AggWrapper$Agg$Mutable$.$anonfun$from$1(AggWrapper.scala:60)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:576)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:574)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1300)
        at mill.api.AggWrapper$Agg$Mutable$.from(AggWrapper.scala:60)
        at mill.api.AggWrapper$Agg$.from(AggWrapper.scala:56)
        at mill.eval.EvaluatorCore.evaluate0(EvaluatorCore.scala:170)
        at mill.eval.EvaluatorCore.$anonfun$evaluate$1(EvaluatorCore.scala:43)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at mill.eval.EvaluatorCore.evaluate(EvaluatorCore.scala:34)
        at mill.eval.EvaluatorCore.evaluate$(EvaluatorCore.scala:26)
        at mill.eval.EvaluatorImpl.evaluate(EvaluatorImpl.scala:15)
        at mill.main.RunScript$.evaluateNamed(RunScript.scala:38)
        at mill.main.RunScript$.$anonfun$evaluateTasksNamed$2(RunScript.scala:26)
        at scala.util.Either.map(Either.scala:382)
        at mill.main.RunScript$.evaluateTasksNamed(RunScript.scala:26)
        at mill.runner.MillBuildBootstrap$.evaluateWithWatches(MillBuildBootstrap.scala:399)
        at mill.runner.MillBuildBootstrap.$anonfun$processFinalTargets$3(MillBuildBootstrap.scala:308)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at mill.runner.MillBuildBootstrap.processFinalTargets(MillBuildBootstrap.scala:308)
        at mill.runner.MillBuildBootstrap.evaluateRec(MillBuildBootstrap.scala:196)
        at mill.runner.MillBuildBootstrap.evaluate(MillBuildBootstrap.scala:48)
        at mill.runner.MillMain$.$anonfun$main0$6(MillMain.scala:234)
        at mill.runner.Watching$.watchLoop(Watching.scala:27)
        at mill.runner.MillMain$.$anonfun$main0$1(MillMain.scala:219)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at scala.Console$.withErr(Console.scala:193)
        at mill.api.SystemStreams$.$anonfun$withStreams$2(SystemStreams.scala:62)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at scala.Console$.withOut(Console.scala:164)
        at mill.api.SystemStreams$.$anonfun$withStreams$1(SystemStreams.scala:61)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
        at scala.Console$.withIn(Console.scala:227)
        at mill.api.SystemStreams$.withStreams(SystemStreams.scala:60)
        at mill.runner.MillMain$.main0(MillMain.scala:101)
        at mill.runner.MillServerMain$.main0(MillServerMain.scala:83)
        at mill.runner.MillServerMain$.main0(MillServerMain.scala:35)
        at mill.runner.Server.$anonfun$handleRun$1(MillServerMain.scala:187)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```
Second and subsequent incarnations of `vecxt.jvm.prepareOffline ` succeed, I suspect because something is correctly cached. 

I can reproduce, by cleaning and re-running the command. It's also with `-j 1`, so I hope easier to work with.

I now suspect, it can be minimised further, but that's the best I have for right now - I'll have a look at something truly minimal in the coming days, if I can...

**Comment by lefou** [comment]
Thanks for the reproducer!

**Comment by lefou** [comment]
@Quafadas I have a quick fix for you to try. It should solve your issue, although the solution should be discusses and improved.

**Comment by Quafadas** [comment]
Er - blimey. that as quick. Once the CI goes though I'll try and track down the hash, and take it for spin :-)... 

Cool - thanks!

**Comment by lefou** [comment]
Minimized reproduction:

```scala
import mill._, mill.scalalib._
import mill.define.ModuleRef

val repos = T.task {
  Seq(
    coursier.maven.MavenRepository("https://repo1.maven.org/maven2"),
    coursier.LocalRepositories.ivy2Local
  )
}

object CustomZincWorkerModule extends ZincWorkerModule with CoursierModule {
  def repositoriesTask = repos
}

object foo extends JavaModule {
  def repositoriesTask = repos
  def zincWorker       = ModuleRef(CustomZincWorkerModule)
}
```

**Comment by Quafadas** [comment]
@lefou thankyou! Looked a little more painful than expected... but👏, very excited to try it.
