### ISSUE TITLE
Scala 3 console doesn't work properly when `ivyDeps` includes JNA on macOS

### ISSUE THREAD

**Issue by mrdziuban** [com-lihaoyi/mill#2960]
See this repo for a minimal reproduction: https://github.com/mrdziuban/mill-scala-3-console-jna

Running the Scala 3 console while depending on `ivy"net.java.dev.jna:jna:5.13.0"` results in `>....` as the prompt instead of the typical `scala>` prompt. Hitting enter then yields a "Bad address" error

<img width="815" alt="image" src="https://github.com/com-lihaoyi/mill/assets/4718399/2ca9bce6-9bd1-4ae2-aa61-fa26f4cb98d4">

**Comment by mrdziuban** [comment]
It looks like this is because `mariadb-java-client` depends on `net.java.dev.jna:jna`, and its dependency is conflicting with whatever version of JNA the console is relying on. This fixes the issue: https://github.com/mrdziuban/mill-scala-3-console-mariadb/compare/main...exclude-jna

**Comment by lefou** [comment]
I wonder, if this can be worked around with a customized classpath `consoleClasspath` like the `ammoniteReplClasspath` in used in `repl`.

**Comment by mrdziuban** [comment]
Edited title and description to reflect that this is caused by a dependency on JNA, not MariaDB.

> I wonder, if this can be worked around with a customized classpath `consoleClasspath` like the `ammoniteReplClasspath` is used in `repl`.

I would guess that's the right path forward, but I wouldn't know where to start with it. I'm going to ask around the sbt community to see if anyone knows how they've worked around the issue.

**Comment by lefou** [comment]
Hm, about your reproducer: I actually can't reproduce.

```
> cat build.sc 
import mill._, scalalib._

object example extends RootModule with ScalaModule {
  def scalaVersion = "3.3.1"
  def ivyDeps = Agg(
    ivy"net.java.dev.jna:jna:5.13.0",
  )
}
> mill -i console
[45/45] console 
Welcome to Scala 3.3.1 (17.0.8.1, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                                                                                                                   
scala> println("hello")

hello
                                                                                                                                                                                                                                   
scala> ^D
                                                                                                                                                                                                                                   
```

**Comment by mrdziuban** [comment]
Ah @lefou, I think it's specific to macOS, this line in the stack trace tipped me off:

```
at org.jline.terminal.impl.jna.osx.OsXNativePty.getSize(OsXNativePty.java:82)
```

**Comment by lefou** [comment]
Can you please add a text version of the stacktrace to this issue?

**Comment by mrdziuban** [comment]
Absolutely

```
>....Exception in thread "main" com.sun.jna.LastErrorException: [14] Bad address
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:415)
	at com.sun.jna.Function.invoke(Function.java:361)
	at com.sun.jna.Library$Handler.invoke(Library.java:270)
	at jdk.proxy1/jdk.proxy1.$Proxy0.ioctl(Unknown Source)
	at org.jline.terminal.impl.jna.osx.OsXNativePty.getSize(OsXNativePty.java:82)
	at org.jline.terminal.impl.AbstractPosixTerminal.getSize(AbstractPosixTerminal.java:60)
	at org.jline.terminal.Terminal.getBufferSize(Terminal.java:217)
	at org.jline.reader.impl.LineReaderImpl.doDisplay(LineReaderImpl.java:755)
	at org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:308)
	at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:121)
	at dotty.tools.repl.JLineTerminal.readLine(JLineTerminal.scala:72)
	at dotty.tools.repl.ReplDriver.readLine$1(ReplDriver.scala:157)
	at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:167)
	at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:172)
	at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:211)
	at dotty.tools.repl.ReplDriver.runBody$$anonfun$1(ReplDriver.scala:185)
	at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80)
	at dotty.tools.repl.ReplDriver.runBody(ReplDriver.scala:185)
	at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:172)
	at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:134)
	at dotty.tools.repl.Main$.main(Main.scala:7)
	at dotty.tools.repl.Main.main(Main.scala)
1 targets failed
console java.lang.Exception: Interactive Subprocess Failed (exit code 1)
    mill.util.Jvm$.runSubprocess(Jvm.scala:184)
    mill.util.Jvm$.runSubprocessWithBackgroundOutputs(Jvm.scala:152)
    mill.util.Jvm$.runSubprocess(Jvm.scala:88)
    mill.scalalib.ScalaModule.$anonfun$console$2(ScalaModule.scala:369)
    scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    scala.Console$.withErr(Console.scala:193)
    mill.api.SystemStreams$.$anonfun$withStreams$2(SystemStreams.scala:62)
    scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    scala.Console$.withOut(Console.scala:164)
    mill.api.SystemStreams$.$anonfun$withStreams$1(SystemStreams.scala:61)
    scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    scala.Console$.withIn(Console.scala:227)
    mill.api.SystemStreams$.withStreams(SystemStreams.scala:60)
    mill.scalalib.ScalaModule.$anonfun$console$1(ScalaModule.scala:374)
    mill.define.Task$TraverseCtx.evaluate(Task.scala:71)
```

**Comment by lihaoyi** [comment]
I can reproduce this on my macbook MacOS Sonoma 14.2.1. I get different error messages on the original repro

```
lihaoyi mill-scala-3-console-jna$ ./mill -i console
[build.sc] [49/53] compile
[info] compiling 1 Scala source to /Users/lihaoyi/test/mill-scala-3-console-jna/out/mill-build/compile.dest/classes ...
[info] done compiling
[45/45] console
Welcome to Scala 3.3.1 (17.0.6, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
>....
val res0: Int = 1
Exception in thread "main" com.sun.jna.LastErrorException: [14] Bad address
        at com.sun.jna.Native.invokeVoid(Native Method)
        at com.sun.jna.Function.invoke(Function.java:415)
        at com.sun.jna.Function.invoke(Function.java:361)
        at com.sun.jna.Library$Handler.invoke(Library.java:270)
        at jdk.proxy1/jdk.proxy1.$Proxy0.ioctl(Unknown Source)
        at org.jline.terminal.impl.jna.osx.OsXNativePty.getSize(OsXNativePty.java:82)
        at org.jline.terminal.impl.AbstractPosixTerminal.getSize(AbstractPosixTerminal.java:60)
        at org.jline.terminal.Terminal.getBufferSize(Terminal.java:217)
        at org.jline.reader.impl.LineReaderImpl.doDisplay(LineReaderImpl.java:755)
        at org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:308)
        at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:121)
        at dotty.tools.repl.JLineTerminal.readLine(JLineTerminal.scala:72)
        at dotty.tools.repl.ReplDriver.readLine$1(ReplDriver.scala:157)
        at dotty.tools.repl.ReplDriver.loop$1(ReplDriver.scala:167)
        at dotty.tools.repl.ReplDriver.runUntilQuit$$anonfun$1(ReplDriver.scala:172)
        at dotty.tools.repl.ReplDriver.withRedirectedOutput(ReplDriver.scala:211)
        at dotty.tools.repl.ReplDriver.runBody$$anonfun$1(ReplDriver.scala:185)
        at dotty.tools.runner.ScalaClassLoader$.asContext(ScalaClassLoader.scala:80)
        at dotty.tools.repl.ReplDriver.runBody(ReplDriver.scala:185)
        at dotty.tools.repl.ReplDriver.runUntilQuit(ReplDriver.scala:172)
        at dotty.tools.repl.ReplDriver.tryRunning(ReplDriver.scala:134)
        at dotty.tools.repl.Main$.main(Main.scala:7)
        at dotty.tools.repl.Main.main(Main.scala)
1 targets failed
console java.lang.Exception: Interactive Subprocess Failed (exit code 1)
    mill.util.Jvm$.runSubprocess(Jvm.scala:184)
    mill.util.Jvm$.runSubprocessWithBackgroundOutputs(Jvm.scala:152)
    mill.util.Jvm$.runSubprocess(Jvm.scala:88)
    mill.scalalib.ScalaModule.$anonfun$console$2(ScalaModule.scala:369)
    scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    scala.Console$.withErr(Console.scala:193)
    mill.api.SystemStreams$.$anonfun$withStreams$2(SystemStreams.scala:62)
    scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    scala.Console$.withOut(Console.scala:164)
    mill.api.SystemStreams$.$anonfun$withStreams$1(SystemStreams.scala:61)
    scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    scala.Console$.withIn(Console.scala:227)
    mill.api.SystemStreams$.withStreams(SystemStreams.scala:60)
    mill.scalalib.ScalaModule.$anonfun$console$1(ScalaModule.scala:374)
    mill.define.Task$TraverseCtx.evaluate(Task.scala:71)
```

And on latest master of Mill:

```
lihaoyi mill-scala-3-console-jna$ /Users/lihaoyi/.cache/mill/download/0.12.0-RC2-62-64ba58 -i console
Mill version 0.12.0-RC2-62-64ba58 is different than configured for this directory!
Configured version is 0.11.6 (/Users/lihaoyi/test/mill-scala-3-console-jna/.mill-version)
[55/59] compile
[55] [info] compiling 1 Scala source to /Users/lihaoyi/test/mill-scala-3-console-jna/out/mill-build/compile.dest/classes ...
[55] [warn] /Users/lihaoyi/test/mill-scala-3-console-jna/build.sc:13:92: trait JavaModuleTests in trait JavaModule is deprecated (since Mill 0.11.10): Use JavaTests instead
[55] [warn]   override lazy val millDiscover: _root_.mill.define.Discover = _root_.mill.define.Discover[this.type]
[55] [warn]                                                                                            ^
[55] [warn] one warning found
[55] [info] done compiling
Welcome to Scala 3.3.1 (17.0.6, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
>....val res0: Int = 1
>....val res1: Int = 2
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (ciMethodData.cpp:334), pid=35694, tid=30467
#  Error: ShouldNotReachHere()
#
# JRE version: OpenJDK Runtime Environment Corretto-17.0.6.10.1 (17.0.6+10) (build 17.0.6+10-LTS)
# Java VM: OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 (17.0.6+10-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/lihaoyi/test/mill-scala-3-console-jna/hs_err_pid35694.log
>....
[error occurred during error reporting (), id 0xe0000000, Internal Error (src/hotspot/share/ci/ciMethodData.cpp:334)]

#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-17/issues/
#
[55/55] ================================================================================ console =============================================================================== 12s
1 targets failed
console java.lang.Exception: Interactive Subprocess Failed (exit code 134)
    mill.util.Jvm$.runSubprocess(Jvm.scala:243)
    mill.util.Jvm$.runSubprocessWithBackgroundOutputs(Jvm.scala:207)
    mill.util.Jvm$.runSubprocess(Jvm.scala:112)
    mill.scalalib.ScalaModule.$anonfun$console$1(ScalaModule.scala:435)
    mill.define.Task$TraverseCtx.evaluate(Task.scala:215)
lihaoyi mill-scala-3-console-jna$ java -version
openjdk version "17.0.6" 2023-01-17 LTS
OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 (build 17.0.6+10-LTS, mixed mode, sharing)
```

**Comment by lihaoyi** [comment]
Seems to go away when scalaVersion is set to 3.3.4, so I'm going to call this fixed
