### ISSUE TITLE
Frequent "class not found" errors; concurrent mill instances suspected cause

### ISSUE THREAD

**Issue by nafg** [com-lihaoyi/mill#3454]
Most frequently, it's this:

```
An unexpected error occurred
Exception in thread "MillServerActionRunner" java.lang.ClassNotFoundException: millbuild.build$
    at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    at mill.runner.MillBuildBootstrap$.getRootModule(MillBuildBootstrap.scala:419)
    at mill.runner.MillBuildBootstrap.evaluateRec(MillBuildBootstrap.scala:147)
    at mill.runner.MillBuildBootstrap.$anonfun$evaluate$1(MillBuildBootstrap.scala:49)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    at mill.runner.MillBuildBootstrap.evaluate(MillBuildBootstrap.scala:48)
    at mill.runner.MillMain$.$anonfun$main0$6(MillMain.scala:234)
    at mill.runner.Watching$.watchLoop(Watching.scala:27)
    at mill.runner.MillMain$.$anonfun$main0$1(MillMain.scala:219)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    at mill.api.SystemStreams$.$anonfun$withStreams$5(SystemStreams.scala:78)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    at mill.api.SystemStreams$.$anonfun$withStreams$4(SystemStreams.scala:77)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    at mill.api.SystemStreams$.$anonfun$withStreams$3(SystemStreams.scala:76)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    at scala.Console$.withErr(Console.scala:193)
    at mill.api.SystemStreams$.$anonfun$withStreams$2(SystemStreams.scala:75)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
    at scala.Console$.withOut(Console.scala:164)
    ...
```

But often Mill runs, but then compilation fails with random "not found" and "Symbol 'type XXX' is missing from the classpath" compiler errors.

Mill version: 0.11.12

IDE: IntelliJ, via BSP import, with BSP build automatically on file save usually enabled

I use `tmuxp` with this file:

```yaml
session_name: 'chesednow-disp-dev'
windows:
- start_directory: /home/naftoli/repositories/gitlab.com/chesednow/disp
  window_name: fish
  layout: e438,159x39,0,0[159x19,0,0{143x19,0,0,7,15x19,144,0,6},159x19,0,20{143x19,0,20,8,15x19,144,20,9}]
  panes:
  - mill -j 16 -w app_lrbcol.runBackground
  - docker compose up db
  - sleep 5; mill -j 16 -w app_js.getScalaJs
  - $SHELL
```

`getScalaJs` is a task that triggers webpacking etc. There are shared modules that app_lrbcol (JVM) and app_js (JS) modules depend on transitively (as well as many platform-specific modules)

**Comment by lihaoyi** [comment]
Going to call this hopefully fixed by @alexarchambault 's work adding a coarse grained lock around the out folder
