### ISSUE TITLE
Targets cannot have more than 22 inputs

### ISSUE THREAD

**Issue by lihaoyi** [com-lihaoyi/mill#910]
Otherwise Mill produces the following error:

```
Compiling /Users/lihaoyi/Github/hands-on-scala-programming/build.sc
build.sc:640: exception during macro expansion:
scala.reflect.macros.TypecheckException: functions may not have more than 22 parameters, but 24 given
        at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$3(Typers.scala:44)
        at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$2(Typers.scala:38)
        at scala.reflect.macros.contexts.Typers.doTypecheck$1(Typers.scala:37)
        at scala.reflect.macros.contexts.Typers.$anonfun$typecheck$7(Typers.scala:50)
        at scala.reflect.internal.Trees.wrappingIntoTerm(Trees.scala:1867)
        at scala.reflect.internal.Trees.wrappingIntoTerm$(Trees.scala:1864)
        at scala.reflect.internal.SymbolTable.wrappingIntoTerm(SymbolTable.scala:28)
        at scala.reflect.macros.contexts.Typers.typecheck(Typers.scala:50)
        at scala.reflect.macros.contexts.Typers.typecheck$(Typers.scala:32)
        at scala.reflect.macros.contexts.Context.typecheck(Context.scala:18)
        at scala.reflect.macros.contexts.Context.typecheck(Context.scala:18)
        at mill.define.Applicative$.impl0(Applicative.scala:99)
        at mill.define.Target$.targetImpl(Task.scala:75)
        at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.$anonfun$resolveJavaReflectionRuntime$6(JavaReflectionRuntimes.scala:51)
        at scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime(Macros.scala:758)

    def epub = T{
                ^
build.sc:640: `T.command` definitions must have 1 parameter list
    def epub = T{
        ^
```

This is a bit of an implementation restriction, due to our usage of `TupleN`s and `FunctionN`s in the `T{...}` macro. A workaround is to manually break it up into a small tree structure so each target has a smaller number of direct dependencies, but it would be nice if Mill could do that automatically somehow

**Comment by lefou** [comment]
Can we intercept that error and produce a helpful message to the user about the issue and how to workaround it?
