### ISSUE TITLE
Java OverlappingFileLockException

### ISSUE THREAD

**Issue by vhurryharry** [com-lihaoyi/mill#959]
I am on MacOS Catalina and tried to install Mill by using the command below.

```
sudo curl -L -o /usr/local/bin/mill https://github.com/lihaoyi/mill/releases/download/0.7.3/0.7.3 && sudo chmod +x /usr/local/bin/mill
```

It worked without exception. But when I try to run `mill` command, I am getting this error.

```
Exception in thread "main" java.nio.channels.OverlappingFileLockException
        at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
        at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
        at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1286)
        at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1178)
        at mill.main.client.FileLock.probe(Locks.java:64)
        at mill.main.client.MillClientMain.run(MillClientMain.java:176)
        at mill.main.client.MillClientMain.main0(MillClientMain.java:129)
        at mill.main.client.MillClientMain.main(MillClientMain.java:82)
```

This is my JDK version info.
```
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
```

I've tried changing the mill download version to `0.7.0`, `0.8.0`, but got the same error.
Actually I was using mill without problems before, but started getting this exception after reinstalling the system.

**Comment by lihaoyi** [comment]
Going to call this fixed because the locking strategy has been overhauled a few times since 0.8.0 (e.g. https://github.com/com-lihaoyi/mill/pull/3368) but feel free to open if it still happens
